'use strict';
const fs=require('fs'),path=require('path');const{chromium}=require('playwright');
const BASE='https://plan-ex.ru/erpv2/',U=p=>new URL(p,BASE).href,OUT=path.resolve(process.env.P15_OUT||'P15_trip_modal_discovery_output');fs.mkdirSync(OUT,{recursive:true});
const COMPANY=27,OWNER='p14_owner_260804221827',TRIP='P15 UI рейс полный жизненный цикл';
function creds(){const e=process.env.P15_CREDENTIALS_B64||'';return e?JSON.parse(Buffer.from(e,'base64').toString('utf8')):[]}function sa(){return creds().find(x=>String(x?.role||'').toUpperCase()==='SUPERADMIN')}
async function login(b,u,pw){const c=await b.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1,locale:'ru-RU',timezoneId:'Europe/Moscow'}),p=await c.newPage();let ok=false;try{await p.goto(U('login'),{waitUntil:'domcontentloaded'});await p.locator('input[name="username"],input[name="email"],input[type="text"]').first().fill(u);await p.locator('input[type="password"]').fill(pw);await Promise.all([p.waitForLoadState('domcontentloaded').catch(()=>{}),p.locator('button[type="submit"],input[type="submit"]').first().click()]);await p.waitForTimeout(400);ok=!/\/login(?:[/?#]|$)/.test(p.url())}catch{}return{c,p,ok}}
function candidates(t,v){const a=[...v];for(const m of String(t).matchAll(/[A-Za-z0-9!@#$%^&*()_+\-=]{8,64}/g))a.push(m[0]);return[...new Set(a)].filter(x=>x!==OWNER&&!x.includes('@example.test')&&!/^[a-f0-9]{64}$/i.test(x))}
async function owner(b){const s=sa(),x=await login(b,s.username,s.password);await x.p.goto(U(`superadmin/companies/${COMPANY}/users`),{waitUntil:'domcontentloaded'});const f=x.p.locator(`form[action$="/superadmin/companies/${COMPANY}/owner/reset-password"]`).first(),nav=x.p.waitForNavigation({waitUntil:'domcontentloaded'});await f.evaluate(z=>HTMLFormElement.prototype.submit.call(z));await nav;const vals=await x.p.locator('input,textarea,code,pre,[data-password]').evaluateAll(ns=>ns.map(n=>n.value||n.textContent||'').filter(Boolean)),list=candidates(await x.p.locator('body').innerText(),vals);await x.c.close();for(const q of list){const y=await login(b,OWNER,q);if(y.ok)return y;await y.c.close()}throw Error('owner unavailable')}
(async()=>{const r={status:'FAIL',tripId:null,dialogs:[],forms:[],buttons:[],links:[],consoleErrors:[],pageErrors:[],requestFailures:[],httpFailures:[],error:null};let b,o;try{b=await chromium.launch({headless:true});o=await owner(b);const p=o.p;p.on('console',m=>{if(m.type()==='error')r.consoleErrors.push(m.text())});p.on('pageerror',e=>r.pageErrors.push(String(e.message||e)));p.on('requestfailed',q=>r.requestFailures.push(q.url()));p.on('response',z=>{if(z.status()>=400)r.httpFailures.push({status:z.status(),url:z.url()})});await p.goto(U('company/trips/linear'),{waitUntil:'domcontentloaded'});const row=p.locator('[data-linear-route-id]').filter({hasText:TRIP}).first();if(!(await row.count()))throw Error('trip row missing');r.tripId=Number(await row.getAttribute('data-linear-route-id'));await row.click();await p.waitForTimeout(1000);r.dialogs=await p.locator('[role="dialog"],dialog,.modal,.modal-shell').evaluateAll(ns=>ns.filter(n=>getComputedStyle(n).display!=='none'&&n.getBoundingClientRect().width>0).map(n=>({id:n.id,className:n.className,text:(n.innerText||'').replace(/\s+/g,' ').slice(0,3000)})));r.forms=await p.locator('form').evaluateAll(ns=>ns.filter(n=>n.getBoundingClientRect().width>0).map(n=>({id:n.id,action:n.getAttribute('action'),method:n.method,inputs:[...n.elements].map(e=>({name:e.name,type:e.type,value:e.type==='password'?'[REDACTED]':String(e.value||'').slice(0,200),required:e.required})).filter(x=>x.name)})));r.buttons=await p.locator('button').evaluateAll(ns=>ns.filter(n=>n.getBoundingClientRect().width>0).map(n=>({text:(n.innerText||'').trim(),type:n.type,form:n.getAttribute('form'),dataset:{...n.dataset}})));r.links=await p.locator('a[href]').evaluateAll(ns=>ns.filter(n=>n.getBoundingClientRect().width>0).map(n=>({text:(n.innerText||'').trim(),href:n.getAttribute('href')})));await p.screenshot({path:path.join(OUT,'P15_004_OWNER_trip_modal_discovery_1920x1080.png'),fullPage:false});r.status=r.dialogs.length||r.forms.some(f=>String(f.action||'').includes('/trips/'))?'PASS':'FAIL'}catch(e){r.error={name:e.name||'Error',message:String(e.message||e).slice(0,500)}}finally{if(o?.c)await o.c.close().catch(()=>{});if(b)await b.close().catch(()=>{});fs.writeFileSync(path.join(OUT,'P15_TRIP_MODAL_DISCOVERY.json'),JSON.stringify(r,null,2));console.log('P15_TRIP_MODAL_DISCOVERY='+r.status);process.exitCode=r.status==='PASS'?0:1}})();
