<?php
namespace App\Service;
use PDO;
trait FinanceMatchingRuleValidationTrait
{
 private static function normalizeRule(PDO $pdo,array $data,?array $old=null):array{
  $pick=static fn(string $key,mixed $default=null):mixed=>array_key_exists($key,$data)?$data[$key]:($old[$key]??$default);$name=trim((string)$pick('name',''));if($name==='')throw new \InvalidArgumentException('Название правила обязательно.');$priority=(int)$pick('priority',100);if($priority<1||$priority>100000)throw new \InvalidArgumentException('Приоритет должен быть от 1 до 100000.');$direction=self::nullableString($pick('direction'));if($direction!==null){$direction=strtoupper($direction);if(!in_array($direction,self::ALLOWED_DIRECTIONS,true))throw new \InvalidArgumentException('Недопустимое направление правила.');}$action=(string)$pick('action_type','categorize');if(!in_array($action,self::ALLOWED_ACTION_TYPES,true))throw new \InvalidArgumentException('Недопустимое действие правила.');$inn=self::validateInn(self::nullableString($pick('counterparty_inn')));$from=self::moneyOrNull($pick('amount_from'));$to=self::moneyOrNull($pick('amount_to'));if($from!==null&&$to!==null&&self::cents($from)>self::cents($to))throw new \InvalidArgumentException('Сумма «от» больше суммы «до».');$cfu=self::nullableInt($pick('target_cash_flow_center_id'));$dds=self::nullableInt($pick('target_dds_category_id'));$cash=self::nullableInt($pick('target_cash_account_id'));$employeeType=self::nullableString($pick('target_employee_identity_type'));$employeeId=self::nullableInt($pick('target_employee_identity_id'));$employeeName=self::nullableString($pick('target_employee_name_snapshot'));$employeeRole=self::nullableString($pick('target_employee_role_snapshot'));
  if($action==='categorize'&&$cash!==null)$action='categorize_to_cash';if($action==='categorize_to_cash'&&$cash===null)$action='categorize';if(in_array($action,['transfer_to_cash','categorize_to_cash'],true)){if($direction!==null&&$direction!=='EXPENSE')throw new \InvalidArgumentException('Перевод Банк → Касса применим только к расходу.');$direction='EXPENSE';}
  if($action==='employee_cash_settlement'){
   if(!in_array($employeeType,[FinanceEmployeePaymentService::IDENTITY_TENANT_USER,FinanceEmployeePaymentService::IDENTITY_COMPANY_USER],true)||$employeeId===null||$employeeName===null)throw new \InvalidArgumentException('Для правила взаиморасчётов выберите сотрудника.');
   // Compatibility action name, direct BANK <-> EMPLOYEE semantics. Never persist a cash target for new/edited employee rules.
   $cash=null;
  }else{$employeeType=$employeeId=$employeeName=$employeeRole=null;}
  if($cfu!==null)self::assertCfu($pdo,$cfu);if($dds!==null)self::assertDds($pdo,$dds,$direction);if($cash!==null)self::assertCashAccount($pdo,$cash);if($cfu!==null&&$dds!==null)FinanceStructureService::assertLinkedPair($pdo,$cfu,$dds);if($action==='categorize'&&$cfu===null&&$dds===null)throw new \InvalidArgumentException('Для разнесения выберите ЦФУ и/или статью ДДС.');if($action==='categorize_to_cash'&&($cfu===null||$dds===null||$cash===null))throw new \InvalidArgumentException('Для разнесения с переводом в кассу выберите ЦФУ, статью ДДС и кассу.');if($action==='transfer_to_cash'&&$cash===null)throw new \InvalidArgumentException('Для перевода выберите целевую кассу.');if($action==='employee_cash_settlement'&&($cfu===null||$dds===null))throw new \InvalidArgumentException('Для взаиморасчёта с сотрудником выберите ЦФУ и статью ДДС.');
  return ['name'=>$name,'priority'=>$priority,'direction'=>$direction,'bank_account_id'=>self::nullableInt($pick('bank_account_id')),'counterparty_inn'=>$inn,'counterparty_id'=>self::nullableInt($pick('counterparty_id')),'counterparty_type'=>self::nullableString($pick('counterparty_type')),'invoice_number_pattern'=>self::nullableString($pick('invoice_number_pattern')),'purpose_contains'=>self::nullableString($pick('purpose_contains')),'purpose_regex'=>self::validateRegex(self::nullableString($pick('purpose_regex'))),'amount_from'=>$from,'amount_to'=>$to,'action_type'=>$action,'target_dds_category_id'=>$dds,'target_cash_flow_center_id'=>$cfu,'target_cash_account_id'=>$cash,'target_employee_identity_type'=>$employeeType,'target_employee_identity_id'=>$employeeId,'target_employee_name_snapshot'=>$employeeName,'target_employee_role_snapshot'=>$employeeRole,'target_counterparty_id'=>self::nullableInt($pick('target_counterparty_id')),'target_counterparty_type'=>self::nullableString($pick('target_counterparty_type')),'auto_apply'=>1];
 }
 private static function auditRule(PDO $pdo,int $id,string $action,?array $old,?array $new,array $user):void{FinanceAuditLogService::log($pdo,'finance_matching_rule',$id,$action,$old,$new,(int)($user['id']??0),(string)($user['role']??'system'));}
}
