<?php
namespace App\Service;
use PDO;
trait FinanceMatchingRuleCrudTrait
{
 private static function ruleColumns(PDO $pdo):array{$cols=[];foreach($pdo->query('SHOW COLUMNS FROM finance_matching_rules')->fetchAll(PDO::FETCH_ASSOC) as $row){$cols[(string)$row['Field']]=true;}return $cols;}
 private static function persistedRulePayload(PDO $pdo,array $normalized):array{$cols=self::ruleColumns($pdo);if(($normalized['action_type']??'')==='employee_cash_settlement'&&!isset($cols['target_employee_identity_type']))throw new \RuntimeException('Схема правил не обновлена. Требуется migration 068.');return array_filter($normalized,static fn($v,$k)=>isset($cols[$k]),ARRAY_FILTER_USE_BOTH);}
 public static function fetchRules(PDO $pdo,array $filters=[]):array{$w=['deleted_at IS NULL'];$p=[];if(array_key_exists('active',$filters)){$w[]='active=:active';$p['active']=$filters['active']?1:0;}if(!empty($filters['direction'])){$w[]='(direction=:direction OR direction IS NULL)';$p['direction']=$filters['direction'];}$s=$pdo->prepare('SELECT * FROM finance_matching_rules WHERE '.implode(' AND ',$w).' ORDER BY priority DESC,id ASC');$s->execute($p);return $s->fetchAll(PDO::FETCH_ASSOC);}
 public static function findRule(PDO $pdo,int $id):?array{$s=$pdo->prepare('SELECT * FROM finance_matching_rules WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);$r=$s->fetch(PDO::FETCH_ASSOC);return $r?:null;}
 public static function createRule(PDO $pdo,array $data,array $user):int{$normalized=self::normalizeRule($pdo,$data);$r=self::persistedRulePayload($pdo,$normalized);$columns=array_keys($r);$placeholders=array_map(static fn($k)=>':'.$k,$columns);$columns[]='active';$placeholders[]='1';$columns[]='created_by_user_id';$placeholders[]=':uid';$columns[]='created_by_role';$placeholders[]=':role';$columns[]='updated_by_user_id';$placeholders[]=':uid2';$columns[]='updated_by_role';$placeholders[]=':role2';$q='INSERT INTO finance_matching_rules (`'.implode('`,`',$columns).'`) VALUES ('.implode(',',$placeholders).')';$s=$pdo->prepare($q);$s->execute($r+['uid'=>$user['id']??null,'role'=>$user['role']??null,'uid2'=>$user['id']??null,'role2'=>$user['role']??null]);$id=(int)$pdo->lastInsertId();self::auditRule($pdo,$id,'create',null,$normalized,$user);return $id;}
 public static function updateRule(PDO $pdo,int $id,array $data,array $user):void{$old=self::findRule($pdo,$id);if(!$old)throw new \InvalidArgumentException('Правило не найдено.');$normalized=self::normalizeRule($pdo,$data,$old);$r=self::persistedRulePayload($pdo,$normalized);$set=[];$p=['id'=>$id,'uid'=>$user['id']??null,'role'=>$user['role']??null];foreach($r as $k=>$v){$set[]="`$k`=:$k";$p[$k]=$v;}$set[]='updated_by_user_id=:uid';$set[]='updated_by_role=:role';$s=$pdo->prepare('UPDATE finance_matching_rules SET '.implode(',',$set).' WHERE id=:id AND deleted_at IS NULL');$s->execute($p);self::auditRule($pdo,$id,'update',$old,$normalized,$user);}
 public static function setActive(PDO $pdo,int $id,bool $active,array $user):void{$old=self::findRule($pdo,$id);if(!$old)throw new \InvalidArgumentException('Правило не найдено.');$s=$pdo->prepare('UPDATE finance_matching_rules SET active=?,updated_by_user_id=?,updated_by_role=? WHERE id=? AND deleted_at IS NULL');$s->execute([$active?1:0,$user['id']??null,$user['role']??null,$id]);self::auditRule($pdo,$id,'toggle',['active'=>(int)$old['active']],['active'=>$active?1:0],$user);}
 public static function setPriority(PDO $pdo,int $id,int $priority,array $user):void{if($priority<1||$priority>100000)throw new \InvalidArgumentException('Некорректный приоритет.');$old=self::findRule($pdo,$id);if(!$old)throw new \InvalidArgumentException('Правило не найдено.');$s=$pdo->prepare('UPDATE finance_matching_rules SET priority=?,updated_by_user_id=?,updated_by_role=? WHERE id=? AND deleted_at IS NULL');$s->execute([$priority,$user['id']??null,$user['role']??null,$id]);self::auditRule($pdo,$id,'priority',['priority'=>(int)$old['priority']],['priority'=>$priority],$user);}
 public static function deleteRule(PDO $pdo,int $id,array $user):array{$own=false;if(!$pdo->inTransaction()){$pdo->beginTransaction();$own=true;}try{$s=$pdo->prepare('SELECT * FROM finance_matching_rules WHERE id=? AND deleted_at IS NULL FOR UPDATE');$s->execute([$id]);$old=$s->fetch(PDO::FETCH_ASSOC);if(!$old)throw new \InvalidArgumentException('Правило не найдено.');$bankReverted=0;$operationsReverted=0;if(($old['action_type']??'categorize')==='categorize'){$bank=$pdo->prepare("UPDATE bank_transactions SET cash_flow_center_id=NULL,dds_category_id=NULL,classification_status='UNALLOCATED',classification_rule_id=NULL,classification_locked=0,classification_updated_at=NOW() WHERE classification_rule_id=? AND UPPER(COALESCE(classification_status,''))='AUTO' AND COALESCE(classification_locked,0)=0 AND COALESCE(is_internal_transfer,0)=0");$bank->execute([$id]);$bankReverted=$bank->rowCount();$ops=$pdo->prepare("UPDATE finance_operations SET cash_flow_center_id=NULL,dds_category_id=NULL,classification_status='UNALLOCATED',classification_rule_id=NULL,classification_locked=0,classification_updated_at=NOW() WHERE classification_rule_id=? AND UPPER(COALESCE(classification_status,''))='AUTO' AND COALESCE(classification_locked,0)=0 AND UPPER(COALESCE(operation_type,''))<>'TRANSFER'");$ops->execute([$id]);$operationsReverted=$ops->rowCount();}$s=$pdo->prepare('UPDATE finance_matching_rules SET active=0,deleted_at=NOW(),updated_by_user_id=?,updated_by_role=? WHERE id=? AND deleted_at IS NULL');$s->execute([$user['id']??null,$user['role']??null,$id]);self::auditRule($pdo,$id,'remove',['active'=>(int)$old['active']],['active'=>0,'removed'=>true,'auto_bank_reverted'=>$bankReverted,'auto_operations_reverted'=>$operationsReverted],$user);if($own)$pdo->commit();return ['bank_transactions'=>$bankReverted,'finance_operations'=>$operationsReverted];}catch(\Throwable $e){if($own&&$pdo->inTransaction())$pdo->rollBack();throw $e;}}
}
