-- Migration 023: Placeholder for superadmin vehicle stats
-- Statistics are updated in PHP code, not in SQL.
-- This file exists to keep the migration sequence consistent.
-- No-op placeholder (no SELECT to avoid unbuffered results with PDO::exec)
