-- Migration 075: employee-held cash pays an incoming invoice.
-- One linked event: employee RETURN -> technical TRANSFER IN Main Cash -> CASH EXPENSE -> invoice allocations.

CREATE TABLE IF NOT EXISTS `finance_employee_invoice_payments` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `event_group_id` VARCHAR(64) NOT NULL,
    `employee_identity_type` VARCHAR(32) NOT NULL,
    `employee_identity_id` INT UNSIGNED NOT NULL,
    `employee_name_snapshot` VARCHAR(255) NOT NULL,
    `employee_role_snapshot` VARCHAR(64) DEFAULT NULL,
    `invoice_id` INT UNSIGNED NOT NULL,
    `invoice_number_snapshot` VARCHAR(100) DEFAULT NULL,
    `counterparty_name_snapshot` VARCHAR(255) DEFAULT NULL,
    `operation_date` DATE NOT NULL,
    `amount` DECIMAL(14,2) NOT NULL,
    `currency` CHAR(3) NOT NULL DEFAULT 'RUR',
    `employee_movement_id` INT UNSIGNED NOT NULL,
    `receipt_finance_operation_id` INT UNSIGNED NOT NULL,
    `expense_finance_operation_id` INT UNSIGNED NOT NULL,
    `comment` TEXT DEFAULT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'POSTED',
    `cancelled_at` DATETIME DEFAULT NULL,
    `cancelled_by_user_id` INT UNSIGNED DEFAULT NULL,
    `cancelled_by_role` VARCHAR(20) DEFAULT NULL,
    `cancellation_reason` VARCHAR(500) DEFAULT NULL,
    `created_by_user_id` INT UNSIGNED DEFAULT NULL,
    `created_by_role` VARCHAR(20) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_feip_event_group` (`event_group_id`),
    UNIQUE KEY `uk_feip_employee_movement` (`employee_movement_id`),
    UNIQUE KEY `uk_feip_receipt_operation` (`receipt_finance_operation_id`),
    UNIQUE KEY `uk_feip_expense_operation` (`expense_finance_operation_id`),
    KEY `idx_feip_employee_date` (`employee_identity_type`,`employee_identity_id`,`operation_date`),
    KEY `idx_feip_invoice` (`invoice_id`,`status`),
    KEY `idx_feip_status_date` (`status`,`operation_date`),
    CONSTRAINT `fk_feip_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `finance_invoices` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_feip_employee_movement` FOREIGN KEY (`employee_movement_id`) REFERENCES `finance_employee_movements` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_feip_receipt_operation` FOREIGN KEY (`receipt_finance_operation_id`) REFERENCES `finance_operations` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_feip_expense_operation` FOREIGN KEY (`expense_finance_operation_id`) REFERENCES `finance_operations` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
