<?php
/** @var DriverService $service */
requireRole(['company_owner', 'senior_logist', 'logist']);
$companyId = $service->getCompanyId();
if ($companyId <= 0) { http_response_code(404); echo '<div class="notice warn">Компания не найдена.</div>'; exit; }
try {
    $company = $service->loadCompany($companyId);
    if (!$company || $company['status'] !== 'active') { http_response_code(404); echo '<div class="notice warn">Компания не найдена или не активна.</div>'; exit; }
    $localPdo = $service->getLocalPdo($company);
    $driver = $service->getDriverById($localPdo, (int)$id);
    if (!$driver) { http_response_code(404); echo '<div class="notice warn">Водитель не найден.</div>'; exit; }
    $role = $_SESSION['role_code'] ?? ''; $canEdit = false;
    if ($role === 'company_owner' || $role === 'senior_logist') $canEdit = true;
    elseif ($role === 'logist') { $userId = (int)$_SESSION['user_id']; if ((int)$driver['created_by_user_id'] === $userId) $canEdit = true; else { $gc = $localPdo->prepare("SELECT access_level FROM entity_access_grants WHERE entity_type='driver' AND entity_id=? AND granted_to_user_id=? AND revoked_at IS NULL LIMIT 1"); $gc->execute([(int)$id, $userId]); $gr = $gc->fetch(PDO::FETCH_ASSOC); if ($gr && $gr['access_level'] === 'edit') $canEdit = true; } }
    if (!$canEdit) { http_response_code(403); echo '<div class="notice warn">У вас нет права редактировать эту запись.</div>'; exit; }
    $phones = $service->getDriverPhones($localPdo, (int)$id);
    $allDocs = $service->getDriverDocuments($localPdo, (int)$id); $docsByType = $service->getDocsByType($localPdo, $allDocs);
    $docTypes = $service->getDocTypes($localPdo);
    $errors=[];$old=$_POST;
    $fullName=trim($_POST['full_name']??'');
    if($fullName===''){$errors['full_name']='Обязательное поле';}else{$fullName=preg_replace('/\s+/',' ',$fullName);$parts=explode(' ',$fullName);if(count($parts)!==3)$errors['full_name']='ФИО должно состоять из трёх слов';else{$titleCase=function($w){return mb_strtoupper(mb_substr($w,0,1)).mb_strtolower(mb_substr($w,1));};$fullName=implode(' ',array_map($titleCase,$parts));}}
    $phone=trim($_POST['phone']??'');if($phone!==''){$digits=preg_replace('/\D/','',$phone);if(strlen($digits)===11&&$digits[0]==='8')$digits='7'.substr($digits,1);if(strlen($digits)===10)$digits='7'.$digits;if(strlen($digits)===11&&$digits[0]==='7'){$phone='+7 '.substr($digits,1,3).' '.substr($digits,4,3).'-'.substr($digits,7,2).'-'.substr($digits,9,2);}}
    $email=trim($_POST['email']??'');if($email!==''){$email=mb_strtolower($email);if(!preg_match('/^[^\s@]+@[^\s@]+\.[^\s@]+$/',$email))$errors['email']='Неверный формат email';}
    $passportNumber=trim($_POST['passport_number']??'');if($passportNumber!==''){$digits=preg_replace('/\D/','',$passportNumber);if(strlen($digits)===10)$passportNumber=substr($digits,0,4).' '.substr($digits,4);}
    $passportDeptCode=trim($_POST['passport_department_code']??'');if($passportDeptCode!==''){$digits=preg_replace('/\D/','',$passportDeptCode);if(strlen($digits)===6)$passportDeptCode=substr($digits,0,3).'-'.substr($digits,3);}
    $passportIssuedBy=trim($_POST['passport_issued_by']??'');$passportIssueDate=trim($_POST['passport_issue_date']??'');
    $licenseNumber=trim($_POST['license_number']??'');if($licenseNumber!==''){$digits=preg_replace('/\D/','',$licenseNumber);if(strlen($digits)===10)$licenseNumber=substr($digits,0,4).' '.substr($digits,4);}
    $licenseIssueDate=trim($_POST['license_issue_date']??'');
    $snils=trim($_POST['snils']??'');if($snils!==''){$digits=preg_replace('/\D/','',$snils);if(strlen($digits)===11)$snils=substr($digits,0,3).'-'.substr($digits,3,3).'-'.substr($digits,6,3).' '.substr($digits,9);}
    $comments=trim($_POST['comments']??'');
    if(!empty($errors)){header('Content-Type: text/html; charset=utf-8');require base_path('app/View/partials/company_driver_modal_edit.php');exit;}
    $localPdo->prepare('UPDATE drivers SET full_name=:full_name,phone=:phone,email=:email,passport_number=:passport_number,passport_department_code=:passport_department_code,passport_issued_by=:passport_issued_by,passport_issue_date=:passport_issue_date,license_number=:license_number,license_issue_date=:license_issue_date,snils=:snils,comments=:comments,updated_by_user_id=:updated_by_user_id,updated_by_role=:updated_by_role WHERE id=:id')->execute([
        ':full_name'=>$fullName,':phone'=>$phone?:null,':email'=>$email?:null,':passport_number'=>$passportNumber?:null,':passport_department_code'=>$passportDeptCode?:null,':passport_issued_by'=>$passportIssuedBy?:null,':passport_issue_date'=>$passportIssueDate?:null,':license_number'=>$licenseNumber?:null,':license_issue_date'=>$licenseIssueDate?:null,':snils'=>$snils?:null,':comments'=>$comments?:null,':updated_by_user_id'=>(int)$_SESSION['user_id'],':updated_by_role'=>$_SESSION['role_code']??null,':id'=>(int)$id]);
    $localPdo->prepare("DELETE FROM driver_phones WHERE driver_id=? AND is_main=0")->execute([(int)$id]);
    $extraPhones=$_POST['extra_phones']??[];$extraComments=$_POST['extra_phone_comments']??[];
    $insPhone=$localPdo->prepare("INSERT INTO driver_phones(driver_id,phone,is_main,comment,created_by_user_id,created_by_role) VALUES(?,?,0,?,?,?)");
    $uid=(int)$_SESSION['user_id'];$urole=$_SESSION['role_code']??null;
    foreach($extraPhones as $idx=>$ep){$ep=trim($ep);if($ep==='')continue;$comment=trim($extraComments[$idx]??'');$insPhone->execute([(int)$id,$ep,$comment,$uid,$urole]);}
    $mainPhoneCheck=$localPdo->prepare("SELECT id FROM driver_phones WHERE driver_id=? AND is_main=1 LIMIT 1");$mainPhoneCheck->execute([(int)$id]);$mainPhoneRow=$mainPhoneCheck->fetch(PDO::FETCH_ASSOC);
    if($mainPhoneRow&&!empty($phone))$localPdo->prepare("UPDATE driver_phones SET phone=? WHERE id=?")->execute([$phone,$mainPhoneRow['id']]);
    elseif(!empty($phone))$localPdo->prepare("INSERT INTO driver_phones(driver_id,phone,is_main,comment,created_by_user_id,created_by_role) VALUES(?,?,1,'',?,?)")->execute([(int)$id,$phone,$uid,$urole]);
    $allowedExts=['pdf','doc','docx','rtf','odt','xls','xlsx','csv','ods','jpg','jpeg','png','webp','gif','bmp','tif','tiff','heic','heif','txt'];$maxFileSizeDoc=20*1024*1024;$storageBase='companies/'.$companyId.'/documents/driver/'.(int)$id;
    $predefDocTypeNames=['passport'=>'Паспорт','driver_license'=>'Водительское удостоверение','snils'=>'СНИЛС'];
    $deleteExistingDocs=$_POST['delete_existing_doc']??[];foreach($deleteExistingDocs as $docId=>$val){if($val!=='1')continue;$localPdo->prepare("UPDATE documents SET deleted_at=NOW(),deleted_by_user_id=?,delete_comment='Archived via modal edit' WHERE id=? AND entity_type='driver' AND entity_id=? AND deleted_at IS NULL")->execute([(int)$_SESSION['user_id'],(int)$docId,(int)$id]);}
    if(!empty($_FILES['existing_doc_file']['name'])&&is_array($_FILES['existing_doc_file']['name'])){foreach($_FILES['existing_doc_file']['name'] as $docId=>$origName){$uploadError=$_FILES['existing_doc_file']['error'][$docId]??UPLOAD_ERR_NO_FILE;if($uploadError!==UPLOAD_ERR_OK||trim((string)$origName)==='')continue;$size=(int)($_FILES['existing_doc_file']['size'][$docId]??0);if($size>$maxFileSizeDoc)continue;$ext=strtolower(pathinfo($origName,PATHINFO_EXTENSION));if(!in_array($ext,$allowedExts,true))continue;$tmp=$_FILES['existing_doc_file']['tmp_name'][$docId]??'';if($tmp==='')continue;$docStmt=$localPdo->prepare("SELECT id,document_type FROM documents WHERE id=? AND entity_type='driver' AND entity_id=? AND deleted_at IS NULL LIMIT 1");$docStmt->execute([(int)$docId,(int)$id]);$existingDoc=$docStmt->fetch(PDO::FETCH_ASSOC);if(!$existingDoc)continue;
$storedName=uniqid('doc_',true).'.'.$ext;$absoluteDir=storage_path($storageBase);if(!is_dir($absoluteDir))mkdir($absoluteDir,0755,true);$destPath=$absoluteDir.'/'.$storedName;if(!move_uploaded_file($tmp,$destPath))continue;if(!is_file($destPath))continue;
$mime=mime_content_type($destPath)?:'application/octet-stream';try{$localPdo->beginTransaction();$localPdo->prepare("UPDATE documents SET deleted_at=NOW(),deleted_by_user_id=?,delete_comment='Replaced via modal edit' WHERE id=? AND entity_type='driver' AND entity_id=? AND deleted_at IS NULL")->execute([(int)$_SESSION['user_id'],(int)$docId,(int)$id]);$localPdo->prepare("INSERT INTO documents(entity_type,entity_id,document_type,original_name,stored_name,relative_path,mime_type,file_size,status,uploaded_by_user_id,uploaded_by_role) VALUES('driver',?,?,?,?,?,?,?,'uploaded',?,?)")->execute([(int)$id,$existingDoc['document_type']??null,$origName,$storedName,$storageBase.'/'.$storedName,$mime,$size,(int)$_SESSION['user_id'],$_SESSION['role_code']??null]);$localPdo->commit();}catch(\Exception$e){$localPdo->rollBack();if(is_file($destPath))@unlink($destPath);}}}
    if(!empty($_FILES['predef_doc']['name'])){foreach($_FILES['predef_doc']['name'] as $code=>$names){if(!is_array($names))$names=[$names];$typeName=$predefDocTypeNames[$code]??null;if(!$typeName)continue;$hasNewFile=false;foreach($names as $n){if(!empty($n)){$hasNewFile=true;break;}}if(!$hasNewFile)continue;
    $tmpNat=$_FILES['predef_doc']['tmp_name'][$code];$origNat=$_FILES['predef_doc']['name'][$code];$szNat=$_FILES['predef_doc']['size'][$code];$errNat=$_FILES['predef_doc']['error'][$code];if(!is_array($tmpNat)){$tmpNat=[$tmpNat];$origNat=[$origNat];$szNat=[$szNat];$errNat=[$errNat];}$savedFiles=[];foreach($tmpNat as $i=>$tmp){if($errNat[$i]!==UPLOAD_ERR_OK)continue;if($szNat[$i]>$maxFileSizeDoc)continue;$orig=$origNat[$i];$ext=strtolower(pathinfo($orig,PATHINFO_EXTENSION));if(!in_array($ext,$allowedExts))continue;$storedName=uniqid('doc_',true).'.'.$ext;$absoluteDir=storage_path($storageBase);if(!is_dir($absoluteDir))mkdir($absoluteDir,0755,true);$destPath=$absoluteDir.'/'.$storedName;if(!move_uploaded_file($tmp,$destPath))continue;if(!is_file($destPath))continue;$mime=mime_content_type($destPath)?:'application/octet-stream';$savedFiles[]=['sn'=>$storedName,'dp'=>$destPath,'on'=>$orig,'mime'=>$mime,'sz'=>$szNat[$i]];}if(!empty($savedFiles)){try{$localPdo->beginTransaction();$localPdo->prepare("UPDATE documents SET deleted_at=NOW(),deleted_by_user_id=?,delete_comment='Replaced via modal edit' WHERE entity_type='driver' AND entity_id=? AND document_type=? AND deleted_at IS NULL")->execute([(int)$_SESSION['user_id'],(int)$id,$typeName]);foreach($savedFiles as $sf){$localPdo->prepare("INSERT INTO documents(entity_type,entity_id,document_type,original_name,stored_name,relative_path,mime_type,file_size,status,uploaded_by_user_id,uploaded_by_role) VALUES('driver',?,?,?,?,?,?,?,'uploaded',?,?)")->execute([(int)$id,$typeName,$sf['on'],$sf['sn'],$storageBase.'/'.$sf['sn'],$sf['mime'],$sf['sz'],(int)$_SESSION['user_id'],$_SESSION['role_code']??null]);}$localPdo->commit();}catch(\Exception$e){$localPdo->rollBack();foreach($savedFiles as $sf){if(is_file($sf['dp']))@unlink($sf['dp']);}}}}}
    if(!empty($_FILES['custom_doc_file']['name'])){$customTypes=$_POST['custom_doc_type']??[];$tmpNm=$_FILES['custom_doc_file']['tmp_name'];$origNm=$_FILES['custom_doc_file']['name'];$szNm=$_FILES['custom_doc_file']['size'];$errNm=$_FILES['custom_doc_file']['error'];if(!is_array($tmpNm)){$tmpNm=[$tmpNm];$origNm=[$origNm];$szNm=[$szNm];$errNm=[$errNm];}foreach($tmpNm as $i=>$tmp){if($errNm[$i]!==UPLOAD_ERR_OK)continue;if($szNm[$i]>$maxFileSizeDoc)continue;$orig=$origNm[$i];$ext=strtolower(pathinfo($orig,PATHINFO_EXTENSION));if(!in_array($ext,$allowedExts,true))continue;$typeName=trim($customTypes[$i]??'');if($typeName==='')continue;$storedName=uniqid('doc_',true).'.'.$ext;$absoluteDir=storage_path($storageBase);if(!is_dir($absoluteDir))mkdir($absoluteDir,0755,true);if(!move_uploaded_file($tmp,$absoluteDir.'/'.$storedName))continue;$localPdo->prepare("INSERT INTO documents(entity_type,entity_id,document_type,original_name,stored_name,relative_path,mime_type,file_size,status,uploaded_by_user_id,uploaded_by_role) VALUES('driver',?,?,?,?,?,?,?,'uploaded',?,?)")->execute([(int)$id,$typeName,$orig,$storedName,$storageBase.'/'.$storedName,mime_content_type($absoluteDir.'/'.$storedName)?:'application/octet-stream',$szNm[$i],(int)$_SESSION['user_id'],$_SESSION['role_code']??null]);}}
    $driver=$service->getDriverById($localPdo,(int)$id);$phones=$service->getDriverPhones($localPdo,(int)$id);$mainPhone=$service->getMainPhone($localPdo,$phones,$driver);$allDocs=$service->getDriverDocuments($localPdo,(int)$id);$docsByType=$service->getDocsByType($localPdo,$allDocs);$zipAvailable=class_exists('ZipArchive');
    $role = $_SESSION['role_code'] ?? ''; $canEdit = false; $canDelete = false;
    if ($role === 'company_owner' || $role === 'senior_logist') { $canEdit = true; $canDelete = true; }
    elseif ($role === 'logist') { $userId = (int)$_SESSION['user_id']; if ((int)$driver['created_by_user_id'] === $userId) { $canEdit = true; $canDelete = true; } else { $gc = $localPdo->prepare("SELECT access_level FROM entity_access_grants WHERE entity_type='driver' AND entity_id=? AND granted_to_user_id=? AND revoked_at IS NULL LIMIT 1"); $gc->execute([(int)$id, $userId]); $gr = $gc->fetch(PDO::FETCH_ASSOC); if ($gr && $gr['access_level'] === 'edit') $canEdit = true; } }
    header('Content-Type: text/html; charset=utf-8');
    require base_path('app/View/partials/company_driver_modal_view.php');exit;
} catch (\Exception $e) { http_response_code(500); echo '<div class="notice warn">Ошибка сохранения: ' . e($e->getMessage()) . '</div>'; exit; }
