<?php
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
$root = dirname(__DIR__);
$read = static fn(string $path): string => (string) file_get_contents($root . '/' . $path);
$checks = [];
$check = static function (string $name, bool $ok) use (&$checks): void { $checks[] = [$name, $ok]; };
$page=$read('app/View/pages/company_finance_operations.php');
$modal=$read('app/View/partials/company_finance_operation_modal_view.php');
$form=$read('app/View/partials/company_finance_operation_allocate_form.php');
$js=$read('public/assets/js/finance-operation-actions.js');
$routes=$read('app/Http/Routes/company_finance_operations.php');
$allocate=$read('app/Http/Controllers/Company/FinanceOperationActions/allocate_submit.php');
$cancel=$read('app/Http/Controllers/Company/FinanceOperationActions/cancel.php');
$history=$read('app/Http/Controllers/Company/FinanceOperationActions/history.php');
$index=$read('app/Http/Controllers/Company/FinanceOperationActions/index.php');
$modalGet=$read('app/Http/Controllers/Company/FinanceOperationActions/modal_view.php');
$allocateGet=$read('app/Http/Controllers/Company/FinanceOperationActions/modal_allocate_form.php');
$routePayments=$read('app/Http/Controllers/Company/FinanceOperationActions/route_payments.php');
$service=$read('app/Service/FinanceOperationActionService.php');
$check('1 operation_id is present in modal DOM',str_contains($modal,'data-operation-id='));
$check('2 allocate button uses delegated handler',str_contains($js,'[data-operation-allocate-btn]')&&!str_contains($modal,'<script>'));
$check('3 cancel button uses delegated handler',str_contains($js,'[data-operation-cancel-btn]')&&!str_contains($modal,'<script>'));
$check('4 base path is used',str_contains($js,'getErpBasePath')&&str_contains($page,"app_url('/assets/js/finance-operation-actions.js')"));
$check('5 allocate auth',str_contains($allocate,"requireRole(['company_owner'])"));
$check('6 allocate csrf',str_contains($allocate,'verifyCsrfRequest()'));
$check('7 cancel auth',str_contains($cancel,"requireRole(['company_owner'])"));
$check('8 cancel csrf',str_contains($cancel,'verifyCsrfRequest()'));
$check('9 logist denied',!str_contains($allocate,"'logist'")&&!str_contains($cancel,"'logist'"));
$check('10 over remaining rejected',str_contains($allocate,'Сумма распределения превышает остаток операции.'));
$check('11 nonpositive rejected',str_contains($allocate,'Сумма распределения должна быть больше нуля.'));
$check('12 cancelled cannot allocate',str_contains($allocate,"status'] ?? '') !== 'POSTED'"));
$check('13 fully allocated blocked',str_contains($allocateGet,'Операция уже полностью распределена.'));
$check('14 remaining recalculated',str_contains($modal,'remaining_amount')&&str_contains($js,'data-allocation-rest'));
$check('15 allocation statuses separate',str_contains($modal,'allocationStatusLabel'));
$check('16 bank transaction preserved',str_contains($service,'UPDATE finance_operations')&&!str_contains($service,'DELETE FROM bank_transactions'));
$check('17 import preserved',!str_contains($service,'DELETE FROM bank_statement'));
$check('18 repeat cancel idempotent',str_contains($service,"return ['changed' => false"));
$check('19 allocation history',str_contains($service,"entity_type = 'finance_allocation'"));
$check('20 cancel history',str_contains($service,"entity_type = 'finance_operation'"));
$check('21 GET no migrations',!str_contains($index.$modalGet.$allocateGet.$history.$routePayments,'applyLocalMigrations'));
$check('22 safe errors',str_contains($allocate,'Не удалось создать распределение.')&&str_contains($cancel,'Не удалось отменить операцию.'));
$check('23 duplicate guard',str_contains($allocate,'finance_allocation_tokens')&&str_contains($form,'request_token'));
$check('24 disabled state',str_contains($modal,'$allocateAllowed')&&str_contains($modal,'$cancelAllowed')&&str_contains($modal,'disabled'));
$check('25 active allocations block cancel',str_contains($service,'Сначала отмените активные распределения'));
$check('26 POST routes',str_contains($routes,"\$router->post('/company/finance/operations/{id}/allocate'")&&str_contains($routes,"\$router->post('/company/finance/operations/{id}/cancel'"));
$check('27 fragments no scripts',!str_contains($modal,'<script')&&!str_contains($form,'<script'));
$check('28 delegated controller loaded',str_contains($page,'finance-operation-actions.js'));
$check('29 supported targets',str_contains($form,'invoice_id')&&str_contains($form,'linear_route_id')&&str_contains($form,'linear_route_payment_id'));
$check('30 history auto loads',str_contains($js,'history(card.dataset.operationId)'));
$failed=0;foreach($checks as[$name,$ok]){echo($ok?'PASS':'FAIL').' - '.$name.PHP_EOL;if(!$ok)$failed++;}echo'TOTAL='.count($checks).'; FAILED='.$failed.PHP_EOL;exit($failed===0?0:1);
