'use strict';
const fs=require('fs'),path=require('path');const{chromium}=require('playwright');
const BASE=(process.env.P14_BASE_URL||'https://plan-ex.ru/erpv2/').replace(/\/+$/,'/'),U=p=>new URL(p,BASE).href,OUT=path.resolve(process.env.P14_OUT_DIR||'P14_output');fs.mkdirSync(OUT,{recursive:true});const OWNER='p14_owner_260804221827';
function rc(){const e=process.env.P11_CREDENTIALS_B64||'';return e?JSON.parse(Buffer.from(e,'base64').toString('utf8')):[]}function sa(){return rc().find(x=>String(x?.role||'').toUpperCase()==='SUPERADMIN')}
async function lt(b,u,pw){const c=await b.newContext({viewport:{width:1920,height:1080},ignoreHTTPSErrors:true,locale:'ru-RU',timezoneId:'Europe/Moscow'}),p=await c.newPage();let ok=false;try{await p.goto(U('login'),{waitUntil:'domcontentloaded'});await p.locator('input[name="username"],input[name="email"],input[type="text"]').first().fill(u);await p.locator('input[type="password"]').fill(pw);await Promise.all([p.waitForLoadState('domcontentloaded').catch(()=>{}),p.locator('button[type="submit"],input[type="submit"]').first().click()]);await p.waitForTimeout(500);ok=!/\/login(?:[/?#]|$)/i.test(p.url())}catch{}return{ok,c,p}}
function cs(t,v){const a=[...v];for(const m of String(t).matchAll(/[A-Za-z0-9!@#$%^&*()_+\-=]{8,64}/g))a.push(m[0]);return[...new Set(a)].filter(x=>x!==OWNER&&!x.includes('@example.test')&&!/^[a-f0-9]{64}$/i.test(x))}
async function owner(b){const s=sa(),x=await lt(b,s.username,s.password);await x.p.goto(U('superadmin/companies/27/users'),{waitUntil:'domcontentloaded'});const f=x.p.locator('form[action$="/superadmin/companies/27/owner/reset-password"]'),n=x.p.waitForNavigation({waitUntil:'domcontentloaded'});await f.evaluate(z=>HTMLFormElement.prototype.submit.call(z));await n;const v=await x.p.locator('input,textarea,code,pre,[data-password]').evaluateAll(ns=>ns.map(n=>n.value||n.textContent||'').filter(Boolean)),a=cs(await x.p.locator('body').innerText(),v);await x.c.close();for(const q of a){const y=await lt(b,OWNER,q);if(y.ok)return y;await y.c.close()}throw Error('owner unavailable')}
async function set(f,n,v){const x=f.locator(`[name="${n}"]`).first();if(!(await x.count()))return;const tag=await x.evaluate(e=>e.tagName);if(tag==='SELECT')await x.selectOption(v);else await x.fill(v)}
(async()=>{const r={status:'FAIL',existingId:null,response:null,errors:[],formValid:null,finalUrl:null,bodySample:null,error:null};let b,o;try{b=await chromium.launch({headless:true});o=await owner(b);const p=o.p;await p.goto(U('company/vehicle-sets'),{waitUntil:'domcontentloaded'});const existing=p.locator('[data-vehicle-set-id]').filter({hasText:'Т014СТ77'}).first();if(await existing.count()){r.existingId=Number(await existing.getAttribute('data-vehicle-set-id'));r.status='PASS';return}await p.locator('button,a').filter({hasText:/Добавить новый транспорт/i}).first().click();await p.waitForTimeout(300);const f=p.locator('#vehicle-set-create-form');await set(f,'set_type','single');await p.waitForTimeout(500);await set(f,'units[primary][brand]','КАМАЗ');await set(f,'units[primary][model]','5490');await set(f,'units[primary][plate_number]','Т014СТ77');await set(f,'units[primary][vin]','XTC54900000000014');await set(f,'units[primary][diagnostic_card_number]','P14-DC-0014');await set(f,'units[primary][diagnostic_card_date]',new Date(Date.now()-864000000).toISOString().slice(0,10));await set(f,'units[primary][capacity_tons]','20');await set(f,'units[primary][volume_m3]','82');await set(f,'comments','P14 isolated synthetic vehicle');r.formValid=await f.evaluate(x=>x.checkValidity());const responses=[];p.on('response',async z=>{if(z.url().includes('/company/vehicle-sets/create')){let body='';try{body=await z.text()}catch{}responses.push({status:z.status(),url:z.url(),body:body.slice(0,3000)})}});await p.locator('button[type="submit"][form="vehicle-set-create-form"]').click();await p.waitForTimeout(2500);r.response=responses.at(-1)||null;r.finalUrl=p.url();r.errors=await p.locator('.field-msg,.notice,.alert,.error,.invalid-feedback').evaluateAll(ns=>ns.map(n=>(n.innerText||'').trim()).filter(Boolean));r.bodySample=(await p.locator('body').innerText()).replace(/\s+/g,' ').slice(0,2000);await p.screenshot({path:path.join(OUT,'P14_VEHICLE_CREATE_AFTER_SUBMIT_1920x1080.png'),fullPage:false});await p.goto(U('company/vehicle-sets'),{waitUntil:'domcontentloaded'});const row=p.locator('[data-vehicle-set-id]').filter({hasText:'Т014СТ77'}).first();if(await row.count()){r.existingId=Number(await row.getAttribute('data-vehicle-set-id'));r.status='PASS'}else r.status='FAIL'}catch(e){r.error={name:e?.name||'Error',message:String(e?.message||e).slice(0,500)}}finally{if(o?.c)await o.c.close().catch(()=>{});if(b)await b.close().catch(()=>{});fs.writeFileSync(path.join(OUT,'P14_runtime_result.json'),JSON.stringify(r,null,2));console.log(`P14_VEHICLE_CREATE=${r.status}`);process.exitCode=r.status==='PASS'?0:1}})();
