'use strict';
const fs=require('fs'),path=require('path');
const {chromium}=require('playwright');
const BASE=(process.env.P14_BASE_URL||'https://plan-ex.ru/erpv2/').replace(/\/+$/,'/');
const U=p=>new URL(p,BASE).href;
const OUT=path.resolve(process.env.P14_OUT_DIR||'P14_output');fs.mkdirSync(OUT,{recursive:true});
function superadmin(){const e=process.env.P11_CREDENTIALS_B64||'';const a=e?JSON.parse(Buffer.from(e,'base64').toString('utf8')):[];return a.find(x=>String(x?.role||'').toUpperCase()==='SUPERADMIN')}
async function login(ctx,c){const p=await ctx.newPage();await p.goto(U('login'),{waitUntil:'domcontentloaded',timeout:45000});await p.locator('input[name="username"],input[name="email"],input[type="email"],input[type="text"]').first().fill(c.username);await p.locator('input[type="password"]').first().fill(c.password);await Promise.all([p.waitForLoadState('domcontentloaded',{timeout:30000}).catch(()=>{}),p.locator('button[type="submit"],input[type="submit"]').first().click()]);await p.waitForTimeout(700);if(/\/login(?:[/?#]|$)/i.test(p.url()))throw Error('login failed');return p}
(async()=>{const r={status:'FAIL',companyId:27,rows:[],pageForms:[],buttons:[],error:null};let b;try{const c=superadmin();if(!c)throw Error('superadmin unavailable');b=await chromium.launch({headless:true});const x=await b.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1,ignoreHTTPSErrors:true,locale:'ru-RU',timezoneId:'Europe/Moscow'}),p=await login(x,{...c});await p.goto(U('superadmin/companies/27/users'),{waitUntil:'domcontentloaded',timeout:45000});await p.waitForTimeout(700);r.rows=await p.evaluate(()=>{const names=['Тестов Владелец П14','Тестов Старший Логист П14','Тестов Логист Один П14','Тестов Логист Два П14'];const all=[...document.querySelectorAll('tr,.table-row,.card,.user-row,[data-user-id]')];return names.map(name=>{const row=all.find(el=>(el.innerText||'').includes(name));if(!row)return{name,found:false};return{name,found:true,text:(row.innerText||'').trim().replace(/\s+/g,' ').slice(0,900),html:row.outerHTML.slice(0,5000),links:[...row.querySelectorAll('a[href]')].map(a=>({text:(a.textContent||'').trim(),href:a.href})),buttons:[...row.querySelectorAll('button,input[type="button"],input[type="submit"]')].map(a=>({text:(a.textContent||a.value||'').trim(),type:a.type||null,name:a.name||null,formAction:a.formAction||null}))}})});r.pageForms=await p.evaluate(()=>[...document.forms].map(f=>({id:f.id||null,action:f.action||null,method:(f.method||'get').toUpperCase(),fields:[...f.querySelectorAll('input,select,textarea')].map(e=>({name:e.name||null,type:e.type||null,id:e.id||null})),buttons:[...f.querySelectorAll('button,input[type="submit"]')].map(e=>({text:(e.textContent||e.value||'').trim(),name:e.name||null,type:e.type||null}))})));r.buttons=await p.evaluate(()=>[...document.querySelectorAll('button,[role="button"],a.btn')].map(e=>({text:(e.textContent||'').trim().replace(/\s+/g,' ').slice(0,120),id:e.id||null,href:e.href||null})).filter(x=>x.text));await p.screenshot({path:path.join(OUT,'P14_TEST_TENANT_USERS_DISCOVERY_1920x1080.png'),fullPage:false});r.status='PASS';await x.close()}catch(e){r.error={name:e?.name||'Error',message:String(e?.message||e).slice(0,500)}}finally{if(b)await b.close().catch(()=>{});fs.writeFileSync(path.join(OUT,'P14_runtime_result.json'),JSON.stringify(r,null,2));console.log(`P14_ROLE_RESET_DISCOVERY=${r.status}`);process.exitCode=r.status==='PASS'?0:1}})().catch(()=>{console.log('P14_ROLE_RESET_DISCOVERY=FAIL');process.exitCode=1});
