'use strict';
const fs=require('fs'),path=require('path');
const {chromium}=require('playwright');
const BASE=(process.env.P14_BASE_URL||'https://plan-ex.ru/erpv2/').replace(/\/+$/,'/'),U=p=>new URL(p,BASE).href;
const OUT=path.resolve(process.env.P14_OUT_DIR||'P14_output');fs.mkdirSync(OUT,{recursive:true});
function superadmin(){const e=process.env.P11_CREDENTIALS_B64||'';const a=e?JSON.parse(Buffer.from(e,'base64').toString('utf8')):[];return a.find(x=>String(x?.role||'').toUpperCase()==='SUPERADMIN')}
async function login(ctx,u,pw){const p=await ctx.newPage();await p.goto(U('login'),{waitUntil:'domcontentloaded',timeout:45000});await p.locator('input[name="username"],input[name="email"],input[type="email"],input[type="text"]').first().fill(u);await p.locator('input[type="password"]').first().fill(pw);await Promise.all([p.waitForLoadState('domcontentloaded',{timeout:30000}).catch(()=>{}),p.locator('button[type="submit"],input[type="submit"]').first().click()]);await p.waitForTimeout(700);if(/\/login(?:[/?#]|$)/i.test(p.url()))throw Error('login failed');return p}
function extract(text){for(const re of [/(?:новый|временный|сгенерированный)\s+пароль\s*[:—-]\s*([^\s<]+)/iu,/пароль\s*[:—-]\s*([A-Za-z0-9!@#$%^&*()_+\-=]{8,})/u]){const m=String(text||'').match(re);if(m)return m[1]}return null}
(async()=>{const r={status:'FAIL',companyId:27,ownerUserId:16,resetHttpStatus:null,passwordLocated:false,ownerLoginPass:false,candidateLengths:[],error:null};let b;try{const c=superadmin();if(!c)throw Error('superadmin unavailable');b=await chromium.launch({headless:true});const sctx=await b.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1,ignoreHTTPSErrors:true,locale:'ru-RU',timezoneId:'Europe/Moscow'}),sp=await login(sctx,c.username,c.password);await sp.goto(U('superadmin/companies/27/users'),{waitUntil:'domcontentloaded',timeout:45000});const form=sp.locator('form[action$="/superadmin/companies/27/owner/reset-password"]').first();if(!(await form.count()))throw Error('owner reset form unavailable');const nav=sp.waitForNavigation({waitUntil:'domcontentloaded',timeout:30000});await form.evaluate(f=>HTMLFormElement.prototype.submit.call(f));const resp=await nav;r.resetHttpStatus=resp?.status()??null;await sp.waitForTimeout(700);let pw=extract(await sp.locator('body').innerText().catch(()=>''));if(!pw){const vals=await sp.locator('input,textarea,code,pre,[data-password]').evaluateAll(ns=>ns.map(n=>n.value||n.getAttribute('data-password')||n.textContent||'').filter(Boolean));r.candidateLengths=vals.map(v=>String(v).length).filter(n=>n>=8&&n<=100);for(const v of vals){pw=extract(`Пароль: ${v}`)||pw;if(pw)break}}if(!pw)throw Error('generated password not located');r.passwordLocated=true;await sctx.close();const octx=await b.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1,ignoreHTTPSErrors:true,locale:'ru-RU',timezoneId:'Europe/Moscow'});const op=await login(octx,'p14_owner_260804221827',pw);const dr=await op.goto(U('company/dashboard'),{waitUntil:'domcontentloaded',timeout:45000});r.ownerLoginPass=dr.status()===200&&!/\/login(?:[/?#]|$)/i.test(op.url());await op.screenshot({path:path.join(OUT,'P14_OWNER_AFTER_PASSWORD_RESET_1920x1080.png'),fullPage:false});pw='';r.status=r.ownerLoginPass?'PASS':'FAIL';await octx.close()}catch(e){r.error={name:e?.name||'Error',message:String(e?.message||e).replace(/[A-Za-z0-9!@#$%^&*()_+\-=]{12,}/g,'[REDACTED]').slice(0,500)}}finally{if(b)await b.close().catch(()=>{});fs.writeFileSync(path.join(OUT,'P14_runtime_result.json'),JSON.stringify(r,null,2));console.log(`P14_OWNER_RESET=${r.status}`);process.exitCode=r.status==='PASS'?0:1}})().catch(()=>{console.log('P14_OWNER_RESET=FAIL');process.exitCode=1});
