'use strict';

const fs = require('fs');
const path = require('path');
const Module = require('module');

let source = fs.readFileSync(path.join(__dirname, 'P17R_full_runtime.js'), 'utf8');
function replaceOnce(before, after, label) {
  if (source.split(before).length !== 2) throw new Error(`P17R v3 anchor mismatch: ${label || before}`);
  source = source.replace(before, after);
}

replaceOnce("  driver: `${PREFIX}DRIVER_MAIN`,", "  driver: `Uiux_p17r_${RUN_KEY}_ Driver Main`,", 'driver name');
replaceOnce("  driverRestore: `${PREFIX}DRIVER_RESTORE`,", "  driverRestore: `Uiux_p17r_${RUN_KEY}_ Driver Restore`,", 'driver restore name');
replaceOnce("  vehicleSecondaryPlate: `П${String(process.env.GITHUB_RUN_ID || Date.now()).slice(-3)}РР77`,", "  vehicleSecondaryPlate: `АВ${String(process.env.GITHUB_RUN_ID || Date.now()).slice(-4).padStart(4, '0')}77`,", 'trailer plate');
replaceOnce("  ddsCode: `${PREFIX}DDS`.replace(/[^A-Za-z0-9_]/g, '').slice(0, 48),", "  ddsCode: `P17R_DDS_${String(process.env.GITHUB_RUN_ID || Date.now()).slice(-6)}`,", 'dds code');
replaceOnce("  matching: `${PREFIX}MATCHING`,", "  matching: `P17R_MATCH_${String(process.env.GITHUB_RUN_ID || Date.now()).slice(-6)}`,", 'matching name');
replaceOnce("  error: null,\n};", "  expectedRequestAborts: [],\n  error: null,\n};", 'expected request aborts');
replaceOnce("  page.on('requestfailed', (request) => result.requestFailures.push({ role, method: request.method(), url: request.url(), error: request.failure()?.errorText || 'failed' }));", "  page.on('requestfailed', (request) => {\n    const item = { role, method: request.method(), url: request.url(), error: request.failure()?.errorText || 'failed' };\n    if (/ERR_ABORTED/i.test(item.error) && /\\/assets\\//i.test(item.url)) result.expectedRequestAborts.push(item);\n    else result.requestFailures.push(item);\n  });", 'request failure classification');
replaceOnce("  if (type === 'file') return false;\n  if (tag === 'SELECT') {", "  if (type === 'file') return false;\n  if (tag !== 'SELECT' && !(await locator.isVisible())) return false;\n  if (tag === 'SELECT') {", 'hidden inputs');
replaceOnce(
"  return { response, post: responses.at(-1) || null };\n}\nfunction inn10(seed) {",
"  return { response, post: responses.at(-1) || null };\n}\nasync function nativeSubmit(page, form) {\n  const responses = [];\n  const handler = (response) => { if (response.request().method() === 'POST') responses.push({ status: response.status(), url: response.url() }); };\n  page.on('response', handler);\n  const nav = page.waitForNavigation({ waitUntil: 'domcontentloaded', timeout: 30000 }).catch(() => null);\n  await form.evaluate((node) => HTMLFormElement.prototype.submit.call(node));\n  const response = await nav;\n  await page.waitForTimeout(700);\n  page.off('response', handler);\n  return { response, post: responses.at(-1) || null };\n}\nasync function selectDynamic(form, name, value) {\n  const field = form.locator(`[name=\\\"${name}\\\"]`).first();\n  if (!(await field.count())) return false;\n  await field.locator(`option[value=\\\"${String(value)}\\\"]`).waitFor({ state: 'attached', timeout: 7000 });\n  await field.selectOption(String(value));\n  await field.evaluate((node) => node.dispatchEvent(new Event('change', { bubbles: true })));\n  return true;\n}\nfunction inn10(seed) {",
'helpers');
replaceOnce("    'units[primary][brand]': 'КАМАЗ',", "    'units[primary][unit_type]': 'tractor', 'units[primary][brand]': 'КАМАЗ',", 'tractor unit type');
replaceOnce("    'units[secondary][brand]': 'ТОНАР',", "    'units[secondary][unit_type]': 'trailer', 'units[secondary][brand]': 'ТОНАР',", 'trailer unit type');
replaceOnce("'units[primary][diagnostic_card_date]': '01.08.2026'", "'units[primary][diagnostic_card_date]': '2026-08-01'", 'primary date');
replaceOnce("'units[secondary][diagnostic_card_date]': '01.08.2026'", "'units[secondary][diagnostic_card_date]': '2026-08-01'", 'secondary date');
replaceOnce("  await submit(ownerPage, form);", "  await nativeSubmit(ownerPage, form);", 'archive native submit');
replaceOnce("  if (supported) await submit(sa.page, restore);", "  if (supported) await nativeSubmit(sa.page, restore);", 'restore native submit');
replaceOnce("  await fill(form,'direction',cfg.direction); await fill(form,'number',cfg.number); await fill(form,'invoice_date','2026-08-05'); await fill(form,'counterparty_entity_type',cfg.direction==='OUTGOING'?'client':'contractor'); await page.waitForTimeout(100);\n  await fill(form,'counterparty_entity_id',cfg.counterpartyId);", "  await fill(form,'direction',cfg.direction); await fill(form,'number',cfg.number); await fill(form,'invoice_date','2026-08-05'); await fill(form,'counterparty_entity_type',cfg.direction==='OUTGOING'?'client':'contractor');\n  await selectDynamic(form,'counterparty_entity_id',cfg.counterpartyId);", 'dynamic counterparty');
replaceOnce("await fill(form,'basis',N.trip); await fill(form,'link_route_id',tripId);", "await fill(form,'basis',N.trip); await selectDynamic(form,'link_route_id',tripId);", 'dynamic trip link');
replaceOnce("  await page.goto(U('company/finance/invoices'),{waitUntil:'domcontentloaded'}); const visible=(await page.locator('body').innerText()).includes(cfg.number);", "  await page.goto(U('company/finance/invoices'),{waitUntil:'domcontentloaded'}); const search=page.locator('input[type=\\\"search\\\"],input[placeholder*=\\\"Поиск\\\"]').first(); if(await search.count()){await search.fill(cfg.number);await page.waitForTimeout(350);} const visible=(await page.locator('body').innerText()).includes(cfg.number);", 'invoice search');
replaceOnce("await fill(form,'code',N.ddsCode); await fill(form,'name',`${PREFIX}DDS category`); await fill(form,'direction','BOTH'); await fill(form,'sort_order','1717');", "await fill(form,'code',N.ddsCode); await fill(form,'name',`P17R DDS ${RUN_KEY}`); await fill(form,'direction','BOTH'); await fill(form,'sort_order','117');", 'dds constraints');
replaceOnce("await fill(form,'name',N.matching); await fill(form,'priority','1717');", "await fill(form,'name',N.matching); await fill(form,'priority','118');", 'matching constraints');
replaceOnce("await fill(form,'purpose_contains',PREFIX);", "await fill(form,'purpose_contains',`P17R_${String(process.env.GITHUB_RUN_ID || '').slice(-6)}`);", 'matching purpose');
replaceOnce(
"  await trigger.click(); await page.waitForTimeout(250);\n  const modal=page.locator('#cash-operation-create-modal:visible'); const form=modal.locator('form[action=\"/erpv2/company/finance/cash/operation-create\"]:visible').first();\n  if(!(await form.count())){const inv=await page.locator('form').evaluateAll(ns=>ns.map(n=>({action:n.action,visible:n.getBoundingClientRect().width>0})));scenario(result.finance,{scenario_id:scenarioId,entity:'cash-operation',action:type,status:'FAIL',pass:false,error_details:{forms:inv}});return;}",
"  await trigger.click();\n  const modal=page.locator('#cash-operation-create-modal:visible');\n  await modal.waitFor({state:'visible',timeout:5000}).catch(()=>{});\n  const form=modal.locator('form[action$=\"/company/finance/cash/operation-create\"]:visible').first();\n  if(!(await form.count())){const inv=await page.locator('form').evaluateAll(ns=>ns.map(n=>({action:n.action,visible:n.getBoundingClientRect().width>0})));const shot=await screenshot(page,'OWNER','cash',`${type.toLowerCase()}_modal_missing`);scenario(result.finance,{scenario_id:scenarioId,entity:'cash-operation',action:type,url:page.url(),final_url:page.url(),status:'FAIL',pass:false,screenshot:shot,error_details:{forms:inv,body:(await page.locator('body').innerText()).slice(0,1500)}});return;}",
'cash exact modal');
replaceOnce("    const tripId=await createTrip(page,{clientId,contractorId,driverId,vehicleId,executorId}); result.entities.tripId=tripId;\n    await financeScenarios(page,{clientId,contractorId,tripId}); await documentNegativeTests(page); await roleChecks(browser,tripId); await tripDeleteRestore(browser,page,tripId);", "    const tripId=await createTrip(page,{clientId,contractorId,driverId,vehicleId,executorId}); result.entities.tripId=tripId;\n    await roleChecks(browser,tripId); await tripDeleteRestore(browser,page,tripId); await financeScenarios(page,{clientId,contractorId,tripId}); await documentNegativeTests(page);", 'trip lifecycle before finance');
replaceOnce("if(restored){await row.dblclick();await ownerPage.waitForTimeout(300);const text=await ownerPage.locator('#linear-trip-view-modal:visible').innerText();", "if(restored){await row.dblclick();await ownerPage.locator('#linear-trip-view-modal:visible [data-linear-trip-edit-btn],#linear-trip-view-modal:visible').first().waitFor({state:'visible',timeout:7000});await ownerPage.waitForTimeout(800);const text=await ownerPage.locator('#linear-trip-view-modal:visible').innerText();", 'trip restore wait');
replaceOnce("const relations=text.includes(N.client)&&text.includes(N.contractor)&&text.includes(N.driver)&&text.includes(N.vehiclePlate);", "const normalized=text.toLocaleLowerCase('ru-RU');const relations=normalized.includes(N.client.toLocaleLowerCase('ru-RU'))&&normalized.includes(N.contractor.toLocaleLowerCase('ru-RU'))&&normalized.includes(N.driver.toLocaleLowerCase('ru-RU'))&&normalized.includes(N.vehiclePlate.toLocaleLowerCase('ru-RU'));", 'trip relation normalization');
replaceOnce("    scenario(result.crud,{scenario_id:'client-relations',entity:'client',action:'restored relation verification',created_id:clientRestoreId,status:'PASS',pass:true,evidence:'Restored client reappeared in tenant list; main trip client relation verified separately.'});", "    const clientRestoreScenario=result.crud.find((item)=>item.scenario_id==='client-restore'); scenario(result.crud,{scenario_id:'client-relations',entity:'client',action:'restored relation verification',created_id:clientRestoreId,status:clientRestoreScenario?.pass?'PASS':'FAIL',pass:Boolean(clientRestoreScenario?.pass),evidence:'Result is derived from the actual restored client list check.'});", 'client relation factual');

const filename = path.join(__dirname, 'P17R_full_runtime_v3.compiled.js');
const runtimeModule = new Module(filename, module);
runtimeModule.filename = filename;
runtimeModule.paths = module.paths;
runtimeModule._compile(source, filename);
