<?php
requireRole(['company_owner','senior_logist','logist']);$crewId=(int)$crewId;$companyId=(int)(getSessionCompanyId()??0);$errors=[];$formError=null;$success=false;$company=null;$crew=null;$old=$_POST;$drivers=[];$contractors=[];$vehicleSets=[];$entityNotFound=false;
try{$pdo=$db->connection();$s=$pdo->prepare('SELECT * FROM companies WHERE id=?');$s->execute([$companyId]);$company=$s->fetch(PDO::FETCH_ASSOC);if(!$company)throw new RuntimeException('Компания не найдена');$localPdo=(new \App\Core\Database(companyDatabaseConfig($config,$company)))->connection();$s=$localPdo->prepare('SELECT c.*,dvb.driver_id,dvb.vehicle_set_id FROM crews c JOIN driver_vehicle_blocks dvb ON c.driver_vehicle_block_id=dvb.id WHERE c.id=?');$s->execute([$crewId]);$crew=$s->fetch(PDO::FETCH_ASSOC);if(!$crew){$entityNotFound=true;throw new RuntimeException('Исполнитель рейса не найден');}
$uid=(int)($_SESSION['user_id']??0);$isLogist=($_SESSION['role_code']??'')==='logist';if($isLogist&&!hasRouteExecutorAccess($localPdo,$crew,$uid,'edit')){http_response_code(403);exit('Нет доступа к редактированию исполнителя рейса.');}
$contractorId=(int)($_POST['contractor_id']??0);$driverId=(int)($_POST['driver_id']??0);$secondaryDriverId=(int)($_POST['secondary_driver_id']??0);$vehicleSetId=(int)($_POST['vehicle_set_id']??0);$status=$_POST['status']??'active';$comments=trim($_POST['comments']??'');
if(!$contractorId)$errors['contractor_id']='Выберите подрядчика';if(!$driverId)$errors['driver_id']='Выберите водителя';if($secondaryDriverId>0&&$secondaryDriverId===$driverId)$errors['secondary_driver_id']='Водители должны отличаться';if(!$vehicleSetId)$errors['vehicle_set_id']='Выберите транспортный комплект';
if(!$errors){$s=$localPdo->prepare("SELECT primary_vehicle_unit_id FROM vehicle_sets WHERE id=? AND deleted_at IS NULL AND status='active'");$s->execute([$vehicleSetId]);$vehicleId=(int)$s->fetchColumn();if(!$vehicleId)$errors['vehicle_set_id']='Транспортный комплект недоступен.';}
if(!$errors){$localPdo->beginTransaction();try{$s=$localPdo->prepare('SELECT id FROM driver_vehicle_blocks WHERE driver_id=? AND vehicle_set_id=? LIMIT 1');$s->execute([$driverId,$vehicleSetId]);$dvbId=(int)$s->fetchColumn();if(!$dvbId){$i=$localPdo->prepare("INSERT INTO driver_vehicle_blocks(driver_id,vehicle_set_id,status,created_by_user_id,created_by_role) VALUES(?,?,\'active\',?,?)");$i->execute([$driverId,$vehicleSetId,$uid,$_SESSION['role_code']]);$dvbId=(int)$localPdo->lastInsertId();}$dup=$localPdo->prepare('SELECT COUNT(*) FROM crews WHERE contractor_id=? AND driver_vehicle_block_id=? AND id!=?');$dup->execute([$contractorId,$dvbId,$crewId]);if((int)$dup->fetchColumn()>0)throw new RuntimeException('Такой исполнитель рейса уже существует в этой компании.');$u=$localPdo->prepare('UPDATE crews SET contractor_id=?,vehicle_id=?,driver_id=?,secondary_driver_id=?,driver_vehicle_block_id=?,status=?,comments=?,updated_by_user_id=?,updated_by_role=? WHERE id=?');$u->execute([$contractorId,$vehicleId,$driverId,$secondaryDriverId?:null,$dvbId,$status,$comments?:null,$uid,$_SESSION['role_code'],$crewId]);$localPdo->commit();$success=true;}catch(Throwable $e){if($localPdo->inTransaction())$localPdo->rollBack();throw $e;}}
}catch(Throwable $e){$formError=$e->getMessage();}
if(!$success&&$localPdo??null){try{$contractors=$localPdo->query("SELECT id,name,inn FROM contractors WHERE deleted_at IS NULL AND status='active' ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);$drivers=$localPdo->query("SELECT id,full_name,phone FROM drivers WHERE deleted_at IS NULL AND status='active' ORDER BY full_name")->fetchAll(PDO::FETCH_ASSOC);$vehicleSets=$localPdo->query("SELECT vs.id,vs.set_type,vu1.plate_number primary_plate,vu2.plate_number secondary_plate FROM vehicle_sets vs LEFT JOIN vehicle_units vu1 ON vs.primary_vehicle_unit_id=vu1.id LEFT JOIN vehicle_units vu2 ON vs.secondary_vehicle_unit_id=vu2.id WHERE vs.deleted_at IS NULL AND vs.status='active' ORDER BY vs.set_type")->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}}
if($success){header('Location: '.app_url('/company/route-executors/'.$crewId));exit;}ob_start();require base_path('app/View/pages/company_route_executor_edit_v2.php');$content=ob_get_clean();require base_path('app/View/layouts/main.php');
