<?php
requireRole(['company_owner','senior_logist','logist']);
$pageTitle='Исполнители рейса'; $pageContext='Исполнители рейса › Компания'; $companyId=(int)(getSessionCompanyId()??0); $executors=[]; $dbError=null; $hasGrantsButAllArchived=false;
try{$pdo=$db->connection();$s=$pdo->prepare('SELECT * FROM companies WHERE id=?');$s->execute([$companyId]);$company=$s->fetch(PDO::FETCH_ASSOC);if(!$company)throw new RuntimeException('Компания не найдена');if($company['status']==='active'){
$localPdo=(new \App\Core\Database(companyDatabaseConfig($config,$company)))->connection();$isLogist=($_SESSION['role_code']??'')==='logist';
$sql="SELECT c.id crew_id,c.status crew_status,c.created_at crew_created_at,ct.id contractor_id,ct.name contractor_name,d1.id driver_id,d1.full_name driver_name,d1.phone driver_phone,d2.id secondary_driver_id,d2.full_name secondary_driver_name,d2.phone secondary_driver_phone,vs.id vehicle_set_id,vs.set_type,CONCAT(vu1.plate_number,IFNULL(CONCAT(' + ',vu2.plate_number),'')) plates,vu1.plate_number primary_plate,u.full_name created_by_name FROM crews c JOIN contractors ct ON c.contractor_id=ct.id JOIN driver_vehicle_blocks dvb ON c.driver_vehicle_block_id=dvb.id JOIN drivers d1 ON dvb.driver_id=d1.id LEFT JOIN drivers d2 ON c.secondary_driver_id=d2.id JOIN vehicle_sets vs ON dvb.vehicle_set_id=vs.id LEFT JOIN vehicle_units vu1 ON vs.primary_vehicle_unit_id=vu1.id LEFT JOIN vehicle_units vu2 ON vs.secondary_vehicle_unit_id=vu2.id LEFT JOIN users u ON c.created_by_user_id=u.id";
if($isLogist){$uid=(int)$_SESSION['user_id'];$sql.=" WHERE c.created_by_user_id=? OR c.id IN(SELECT entity_id FROM entity_access_grants WHERE entity_type='crew' AND granted_to_user_id=? AND access_level IN('view','edit') AND revoked_at IS NULL) ORDER BY c.created_at DESC";$s=$localPdo->prepare($sql);$s->execute([$uid,$uid]);$executors=$s->fetchAll(PDO::FETCH_ASSOC);}else{$executors=$localPdo->query($sql.' ORDER BY c.created_at DESC')->fetchAll(PDO::FETCH_ASSOC);}
}}
catch(Throwable $e){$company=$company??null;$dbError='Не удалось загрузить исполнителей рейса.';}
ob_start();require base_path('app/View/pages/company_route_executors.php');$content=ob_get_clean();require base_path('app/View/layouts/main.php');
