<?php
requireRole(['company_owner']);$pageTitle='Банковские счета';$pageContext='Финансы › Банковские счета';$companyId=(int)(getSessionCompanyId()??0);$bankFinanceSuccess=$_SESSION['bank_finance_success']??null;$bankFinanceError=$_SESSION['bank_finance_error']??null;unset($_SESSION['bank_finance_success'],$_SESSION['bank_finance_error']);
$company=null;$accounts=[];$imports=[];$transactions=[];$dailyBalances=[];$bankSettings=[];$reconciliation=[];$dbError=null;$txTotal=0;$txPages=1;$txPage=1;$search='';$classificationStatus='';
if($companyId>0){try{$central=$db->connection();$stmt=$central->prepare('SELECT * FROM companies WHERE id=?');$stmt->execute([$companyId]);$company=$stmt->fetch(PDO::FETCH_ASSOC)?:null;
 if($company&&($company['status']??'')==='active'){$pageContext='Финансы › Банковские счета › Компания: '.e($company['name']);$localPdo=(new \App\Core\Database(companyDatabaseConfig($config,$company)))->connection();$accounts=\App\Service\BankFinanceService::getAccounts($localPdo);$imports=\App\Service\BankFinanceService::getImports($localPdo);$dateFrom=$_GET['date_from']??null;$dateTo=$_GET['date_to']??null;$txPage=max(1,(int)($_GET['tx_page']??1));$txPerPage=max(1,min(500,(int)($_GET['tx_per_page']??100)));$search=trim((string)($_GET['q']??''));$classificationStatus=(string)($_GET['classification_status']??'');
  if($classificationStatus===''&&$search!==''){if(preg_match('/вручн/iu',$search))$classificationStatus='MANUAL';elseif(preg_match('/автомат/iu',$search))$classificationStatus='AUTO';elseif(preg_match('/конфликт|провер/iu',$search))$classificationStatus='NEEDS_REVIEW';elseif(preg_match('/не разнес/iu',$search))$classificationStatus='UNALLOCATED';}
  $txResult=\App\Service\FinanceMatchingRuleService::fetchBankRegister($localPdo,['date_from'=>$dateFrom,'date_to'=>$dateTo,'search'=>$search,'classification_status'=>$classificationStatus,'page'=>$txPage,'per_page'=>$txPerPage]);$transactions=$txResult['data'];$txTotal=$txResult['total'];$txPages=max(1,$txResult['pages']);$dailyBalances=\App\Service\BankFinanceService::getDailyBalances($localPdo,null,1,100,$dateFrom,$dateTo)['data'];try{$reconciliation=\App\Service\FinanceBankReconciliationService::reconcileAll($localPdo);}catch(Throwable $e){error_log('Bank reconciliation read error: '.$e->getMessage());}
 }}catch(Throwable $e){error_log('Bank accounts read error: '.$e->getMessage());$dbError='Не удалось загрузить банковские данные компании.';}}
ob_start();require base_path('app/View/pages/company_bank_accounts.php');$content=ob_get_clean();
if(($company['status']??'')==='active'&&$dbError===null){ob_start();require base_path('app/View/partials/company_bank_classification_register.php');$classificationHtml=ob_get_clean();$anchor='<div class="table-card table-card--standard bank-finance-card bank-transactions-card">';$content=str_replace($anchor,$classificationHtml.$anchor,$content);$b='<button type="button" class="btn btn-secondary" data-open-modal="bank-statements-modal">Просмотр выписок</button>';$f='<form method="post" action="'.e(app_url('/company/finance/bank-accounts/refresh-from-mail')).'" class="inline-form">'.csrfField().'<button type="submit" class="btn btn-secondary">Обновить из почты</button></form>';$content=str_replace($b,$b.$f,$content);}
require base_path('app/View/layouts/main.php');
