<?php
$routeExecutorCreateFormMode=$routeExecutorCreateFormMode??'page'; $routeExecutorFormId=$routeExecutorFormId??'route-executor-create-form'; $routeExecutorFormAction=$routeExecutorFormAction??app_url('/company/route-executors/create');
?>
<?php if ($formError): ?><div class="notice warn"><?=e($formError)?></div><?php endif; ?>
<form id="<?=$routeExecutorFormId?>" method="post" action="<?=$routeExecutorFormAction?>" class="<?=$routeExecutorCreateFormMode==='modal'?'':'panel'?>">
<div class="panel-body">
<div class="form-section"><h3 class="panel-head-title">Исполнитель рейса</h3><p class="text-muted mb-section">Подрядчик + экипаж (1–2 водителя) + ТС</p>
<div class="field"><label class="field-label">Подрядчик <span class="req">*</span></label><select name="contractor_id" class="field-input" required><option value="">— Выберите подрядчика —</option><?php foreach($contractors as $x):?><option value="<?=$x['id']?>" <?=($old['contractor_id']??'')==$x['id']?'selected':''?>><?=e($x['name'])?> (ИНН: <?=e($x['inn'])?>)</option><?php endforeach;?></select><?php if(!empty($errors['contractor_id'])):?><div class="field-msg is-error"><?=e($errors['contractor_id'])?></div><?php endif;?></div>
<div class="field"><label class="field-label">Водитель 1 <span class="req">*</span></label><select name="driver_id" class="field-input" required><option value="">— Выберите водителя —</option><?php foreach($drivers as $x):?><option value="<?=$x['id']?>" <?=($old['driver_id']??'')==$x['id']?'selected':''?>><?=e($x['full_name'])?> — <?=e($x['phone'])?></option><?php endforeach;?></select><?php if(!empty($errors['driver_id'])):?><div class="field-msg is-error"><?=e($errors['driver_id'])?></div><?php endif;?></div>
<div class="field"><label class="field-label">Водитель 2 <span class="text-muted">(необязательно)</span></label><select name="secondary_driver_id" class="field-input"><option value="">— Без второго водителя —</option><?php foreach($drivers as $x):?><option value="<?=$x['id']?>" <?=($old['secondary_driver_id']??'')==$x['id']?'selected':''?>><?=e($x['full_name'])?> — <?=e($x['phone'])?></option><?php endforeach;?></select><?php if(!empty($errors['secondary_driver_id'])):?><div class="field-msg is-error"><?=e($errors['secondary_driver_id'])?></div><?php endif;?><p class="field-hint">Если на одной машине одновременно работают два водителя, выберите второго — система сформирует экипаж.</p></div>
<div class="field"><label class="field-label">Транспорт (ТС) <span class="req">*</span></label><select name="vehicle_set_id" class="field-input" required><option value="">— Выберите транспортный комплект —</option><?php foreach($vehicleSets as $x):?><option value="<?=$x['id']?>" <?=($old['vehicle_set_id']??'')==$x['id']?'selected':''?>><?=e(ui_set_type($x['set_type']??null))?> — <?=e($x['primary_plate']??'—')?><?=!empty($x['secondary_plate'])?' + '.e($x['secondary_plate']):''?></option><?php endforeach;?></select><?php if(!empty($errors['vehicle_set_id'])):?><div class="field-msg is-error"><?=e($errors['vehicle_set_id'])?></div><?php endif;?></div>
</div>
<div class="form-section"><h3 class="panel-head-title">Дополнительно</h3><div class="field"><label class="field-label">Комментарий</label><textarea name="comments" class="field-textarea" rows="3"><?=e($old['comments']??'')?></textarea></div></div>
<?php if($routeExecutorCreateFormMode==='page'):?><div class="form-actions"><button type="submit" class="btn btn-primary">Создать исполнителя рейса</button></div><?php else:?><input type="hidden" name="_is_modal" value="1"><div class="form-actions"><button type="submit" class="btn btn-primary">Создать исполнителя рейса</button></div><?php endif;?>
</div></form>
