<?php

use App\Service\FinanceOperationService;
use App\Service\FinanceAllocationService;

$fmtDate = static fn($d) => ($d && $d !== '—') ? date('d.m.Y', strtotime((string) $d) ?: time()) : '—';
$canAllocate = $canAllocate ?? false;
$status = (string) ($operation['status'] ?? '');
$remaining = (float) ($operation['remaining_amount'] ?? 0);
$hasAllocations = !empty($allocations);
$allocateAllowed = $canAllocate && $status === 'POSTED' && $remaining > 0;
$cancelAllowed = $canAllocate && in_array($status, ['POSTED', 'PENDING_CONFIRMATION'], true) && !$hasAllocations;
$allocateReason = $status !== 'POSTED' ? 'Распределять можно только проведённые операции.' : ($remaining <= 0 ? 'Операция уже полностью распределена.' : '');
$cancelReason = $status === 'CANCELLED' ? 'Операция уже отменена.' : ($hasAllocations ? 'Сначала отмените активные распределения.' : '');
?>
<?php if ($error): ?>
<div class="form-alert alert-error"><?= e($error) ?></div>
<?php elseif ($operation): ?>
<div class="finance-operation-card" data-operation-card data-operation-id="<?= (int) $operation['id'] ?>" data-status="<?= e($status) ?>" data-status-label="<?= e(FinanceOperationService::statusLabel($status)) ?>" data-allocation-status-label="<?= e(FinanceOperationService::allocationStatusLabel($operation['allocation_status'] ?? null)) ?>" data-allocated="<?= e((string) ($operation['allocated_amount'] ?? '0.00')) ?>" data-remaining="<?= e((string) ($operation['remaining_amount'] ?? '0.00')) ?>">
    <div class="finance-operation-heading"><div><h3>Операция №<?= (int) $operation['id'] ?></h3><div class="finance-operation-subtitle"><?= $fmtDate($operation['operation_date'] ?? '') ?> · <?= e(FinanceOperationService::operationTypeLabel($operation['operation_type'] ?? null)) ?></div></div><span class="<?= e(FinanceOperationService::statusBadgeClass($status)) ?>"><span class="dot"></span><?= e(FinanceOperationService::statusLabel($status)) ?></span></div>
    <div class="finance-operation-metrics"><div><span>Сумма</span><strong><?= FinanceOperationService::formatAmount($operation['amount'] ?? null) ?> ₽</strong></div><div><span>Разнесено</span><strong><?= FinanceAllocationService::formatAmount($operation['allocated_amount'] ?? null) ?> ₽</strong></div><div><span>Остаток</span><strong><?= FinanceAllocationService::formatAmount($operation['remaining_amount'] ?? null) ?> ₽</strong></div><div><span>Статус разнесения</span><strong><?= e(FinanceOperationService::allocationStatusLabel($operation['allocation_status'] ?? null)) ?></strong></div></div>
    <div class="finance-operation-details"><div><span>Расчётный счёт</span><b><?= e($operation['account_name'] ?? '—') ?></b></div><div><span>Источник</span><b><?= e(FinanceOperationService::sourceLabel($operation['source'] ?? null)) ?></b></div><div><span>Контрагент</span><b><?= e($operation['counterparty_name'] ?? '—') ?></b><?php if (!empty($operation['counterparty_inn'])): ?><small>ИНН <?= e($operation['counterparty_inn']) ?></small><?php endif; ?></div><div class="wide"><span>Назначение платежа</span><b><?= e($operation['purpose'] ?: '—') ?></b></div><?php if (!empty($operation['cancellation_reason'])): ?><div class="wide"><span>Причина отмены</span><b><?= e($operation['cancellation_reason']) ?></b></div><?php endif; ?></div>
    <?php if ($hasAllocations): ?><section class="finance-operation-section"><h4>Распределения</h4><div class="table-scroll"><table class="table"><thead><tr><th>Дата</th><th>Сумма</th><th>Счёт</th><th>Рейс</th><th>Комментарий</th><th></th></tr></thead><tbody><?php foreach ($allocations as $al): ?><tr><td><?= $fmtDate($al['allocation_date'] ?? '') ?></td><td><?= FinanceAllocationService::formatAmount($al['amount'] ?? null) ?> ₽</td><td><?= e($al['invoice_number'] ?? '—') ?></td><td><?= e(trim(($al['route_type'] ?? '') . ' ' . ($al['planned_loading_date'] ?? '')) ?: '—') ?></td><td><?= e($al['comment'] ?? '—') ?></td><td><form action="<?= app_url('/company/finance/operations/allocations/' . (int) $al['id'] . '/cancel') ?>" method="post" data-allocation-cancel-form><?= csrfField() ?><input type="hidden" name="reason" value="Отменено вручную"><button type="submit" class="btn btn-ghost btn-sm">Отменить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
    <section class="finance-operation-section"><div class="finance-operation-section-head"><h4>История изменений</h4><button type="button" class="btn btn-ghost btn-sm" data-operation-history-btn data-operation-id="<?= (int) $operation['id'] ?>">Обновить историю</button></div><div data-operation-history-container><div class="empty-state compact"><p>Загрузка истории…</p></div></div></section>
</div>
<div class="modal-foot is-spaced finance-operation-footer"><button type="button" class="btn btn-ghost" data-close-modal="operation-view-modal">Закрыть</button><div class="modal-foot-actions"><button type="button" class="btn btn-primary" data-operation-allocate-btn data-operation-id="<?= (int) $operation['id'] ?>" data-url="<?= app_url('/company/finance/operations/' . (int) $operation['id'] . '/allocate') ?>" <?= $allocateAllowed ? '' : 'disabled' ?> title="<?= e($allocateReason) ?>">Распределить</button><button type="button" class="btn btn-danger" data-operation-cancel-btn data-operation-id="<?= (int) $operation['id'] ?>" data-url="<?= app_url('/company/finance/operations/' . (int) $operation['id'] . '/cancel') ?>" data-date="<?= e($fmtDate($operation['operation_date'] ?? '')) ?>" data-amount="<?= e(FinanceOperationService::formatAmount($operation['amount'] ?? null) . ' ₽') ?>" data-type="<?= e(FinanceOperationService::operationTypeLabel($operation['operation_type'] ?? null)) ?>" data-counterparty="<?= e($operation['counterparty_name'] ?? '—') ?>" <?= $cancelAllowed ? '' : 'disabled' ?> title="<?= e($cancelReason) ?>">Отменить операцию</button></div></div>
<?php endif; ?>
