CREATE TABLE IF NOT EXISTS deleted_entities (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id INT UNSIGNED NOT NULL,
    company_name VARCHAR(255) DEFAULT NULL,
    local_db VARCHAR(64) DEFAULT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id INT UNSIGNED NOT NULL,
    source_table VARCHAR(64) NOT NULL,
    display_name VARCHAR(512) DEFAULT NULL,
    deleted_by_user_id INT UNSIGNED DEFAULT NULL,
    deleted_by_role VARCHAR(32) DEFAULT NULL,
    deleted_by_name VARCHAR(255) DEFAULT NULL,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(512) DEFAULT NULL,
    snapshot_json LONGTEXT DEFAULT NULL,
    documents_count INT UNSIGNED DEFAULT 0,
    storage_paths_json TEXT DEFAULT NULL,
    status VARCHAR(16) DEFAULT 'archived',
    restored_at TIMESTAMP NULL DEFAULT NULL,
    restored_by_user_id INT UNSIGNED DEFAULT NULL,
    restored_by_role VARCHAR(32) DEFAULT NULL,
    INDEX idx_deleted_entities_company (company_id),
    INDEX idx_deleted_entities_type (entity_type),
    INDEX idx_deleted_entities_status (status),
    INDEX idx_deleted_entities_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
