<?php
requireRole(['company_owner', 'senior_logist', 'logist']);
$companyId=(int)(getSessionCompanyId()??0);$entityType=$_POST['entity_type']??'';$entityId=(int)($_POST['entity_id']??0);
$allowedExt=['pdf','doc','docx','rtf','odt','xls','xlsx','csv','ods','jpg','jpeg','png','webp','gif','bmp','tif','tiff','heic','heif','txt'];$maxSize=20*1024*1024;
if($companyId<=0||$entityType===''||$entityId<=0){header('Location: /company/documents?error=invalid_request');exit;}
try{$pdo=$db->connection();$stmt=$pdo->prepare('SELECT * FROM companies WHERE id=?');$stmt->execute([$companyId]);$company=$stmt->fetch(PDO::FETCH_ASSOC);if(!$company||$company['status']!=='active'){header('Location: /company/documents?entity_type='.urlencode($entityType).'&entity_id='.$entityId);exit;}
$cfg=$config['database'];$cfg['database']=$company['db_identifier'];$ldb=new \App\Core\Database($cfg);$lpdo=$ldb->connection();applyLocalMigrations($lpdo);
$existingIds=$_POST['existing_ids']??[];if(is_array($existingIds)){foreach($existingIds as $eid){$lpdo->prepare("UPDATE documents SET deleted_at=NOW(),deleted_by_user_id=?,delete_comment='Replaced' WHERE id=? AND entity_type=? AND entity_id=?")->execute([(int)$_SESSION['user_id'],(int)$eid,$entityType,$entityId]);}}
if(!empty($_FILES['predef_doc']['name'])&&is_array($_FILES['predef_doc']['name'])){$dt=$_POST['predef_doc_type']??[];foreach($_FILES['predef_doc']['name']as $code=>$names){if(!is_array($names))$names=[$names];$tmpNames=$_FILES['predef_doc']['tmp_name'][$code]??[];if(!is_array($tmpNames))$tmpNames=[$tmpNames];$typeName=$dt[$code]??'';foreach($names as $i=>$origName){if(empty($origName)||$_FILES['predef_doc']['error'][$code][$i]!==UPLOAD_ERR_OK)continue;$ext=strtolower(pathinfo($origName,PATHINFO_EXTENSION));if(!in_array($ext,$allowedExt,true))continue;$fs=$_FILES['predef_doc']['size'][$code][$i]??0;if($fs>$maxSize)continue;$sn=uniqid('doc_',true).'.'.$ext;$rd='companies/'.$companyId.'/documents/'.$entityType.'/'.$entityId;$ad=storage_path($rd);if(!is_dir($ad))mkdir($ad,0755,true);move_uploaded_file($_FILES['predef_doc']['tmp_name'][$code][$i],$ad.DIRECTORY_SEPARATOR.$sn);$mime=mime_content_type($ad.DIRECTORY_SEPARATOR.$sn)?:'application/octet-stream';$lpdo->prepare("INSERT INTO documents(entity_type,entity_id,document_type,original_name,stored_name,relative_path,mime_type,file_size,status,uploaded_by_user_id,uploaded_by_role)VALUES(?,?,?,?,?,?,?,?,'uploaded',?,?)")->execute([$entityType,$entityId,$typeName?:null,$origName,$sn,$rd.'/'.$sn,$mime,$fs,(int)$_SESSION['user_id'],$_SESSION['role_code']??null]);}}}
header('Location: /company/documents?entity_type='.urlencode($entityType).'&entity_id='.$entityId);exit;}
catch(\Exception$e){header('Location: /company/documents?entity_type='.urlencode($entityType).'&entity_id='.$entityId);exit;}
