'use strict';
const { chromium } = require('playwright');
const BASE='https://plan-ex.ru/erpv2/';
const must=(v,m)=>{if(!v)throw new Error(m)};
(async()=>{
 const creds=JSON.parse(Buffer.from(process.env.P12_CREDENTIALS_B64||'','base64').toString('utf8'));
 const owner=creds.find(x=>String(x.role||'').toUpperCase()==='OWNER'); must(owner,'OWNER credentials');
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1920,height:1080},locale:'ru-RU',timezoneId:'Europe/Moscow'});
 const page=await context.newPage();
 const bad=[]; page.on('response',r=>{if(r.status()>=400)bad.push({status:r.status(),url:r.url()})});
 try{
  await page.goto(BASE+'login',{waitUntil:'domcontentloaded'});
  await page.locator('input[name="username"],input[name="email"],input[type="text"]').first().fill(owner.username);
  await page.locator('input[type="password"]').fill(owner.password);
  await page.locator('button[type="submit"],input[type="submit"]').first().click();
  await page.waitForTimeout(700); must(!page.url().includes('/login'),'login failed');
  const r=await page.goto(BASE+'company/finance/bank-accounts',{waitUntil:'networkidle'}); must(r&&r.status()===200,'bank HTTP');
  const recon=await page.request.get(BASE+'company/finance/bank-accounts/reconciliation/json');
  const j=await recon.json(); const summary=j.reconciliation&&j.reconciliation.summary||{};
  console.log('P47_RECON_SUMMARY='+JSON.stringify(summary));
  if(summary.all_ok) must(await page.locator('[data-reconciliation-banner]').count()===0,'success reconciliation banner must be hidden');
  const row=page.locator('tr[data-tx-id]').first(); must(await row.count(),'bank row missing');
  const attrs=await row.evaluate(el=>({id:el.getAttribute('data-tx-id'),url:el.getAttribute('data-classify-url')}));
  console.log('P47_ROW='+JSON.stringify(attrs)); must(attrs.url,'classify url missing');
  await row.dblclick();
  await page.locator('#tx-detail-modal').waitFor({state:'visible'});
  const cfu=page.locator('#tx-detail-modal select[name="cash_flow_center_id"]');
  const dds=page.locator('#tx-detail-modal select[name="dds_category_id"]');
  await cfu.waitFor({state:'visible'}); await dds.waitFor({state:'visible'});
  const cfuOptions=await cfu.locator('option').count(); const ddsOptions=await dds.locator('option').count();
  console.log('P47_ALLOCATION_OPTIONS='+JSON.stringify({cfuOptions,ddsOptions}));
  must(cfuOptions>1,'CFU options missing'); must(ddsOptions>1,'DDS options missing');
  const formAction=await page.locator('#tx-detail-modal form[action*="/bank-transactions/"]').getAttribute('action');
  console.log('P47_FORM_ACTION='+formAction); must(formAction&&formAction.includes('/bank-transactions/'+attrs.id+'/classify'),'wrong classify form action');
  must(!(await page.locator('#tx-detail-modal').innerText()).includes('Банковская операция не найдена'),'operation lookup failed');
  console.log('P47_BAD_RESPONSES='+JSON.stringify(bad));
  must(!bad.some(x=>x.url.includes('/bank-transactions/')&&x.status>=400),'classification request failed');
  console.log('P47_OK');
 }finally{await browser.close()}
})().catch(e=>{console.error(e.stack||e);process.exit(1)});