<?php if($formError):?><div class="notice warn"><?=e($formError)?></div><?php endif;?>
<?php if($entityNotFound):?><div class="notice warn">Исполнитель рейса не найден.</div><?php elseif($crew):?>
<div class="page-head"><div><h1>Редактировать исполнителя рейса</h1><p class="text-muted">Экипаж: одна машина, один или два водителя</p></div><div class="page-head-actions"><a href="<?=app_url('/company/route-executors/'.$crewId)?>" class="btn btn-ghost">← К просмотру</a></div></div>
<form method="post" action="<?=app_url('/company/route-executors/'.$crewId.'/edit')?>" class="panel"><div class="panel-body">
<div class="form-section"><h3 class="panel-head-title">Исполнитель рейса</h3>
<div class="field"><label class="field-label">Подрядчик</label><select name="contractor_id" class="field-input" required><?php foreach($contractors as $x):?><option value="<?=$x['id']?>" <?=((int)($old['contractor_id']??0)==(int)$x['id']?'selected':'')?>><?=e($x['name'])?> (ИНН: <?=e($x['inn'])?>)</option><?php endforeach;?></select></div>
<div class="field"><label class="field-label">Водитель 1</label><select name="driver_id" class="field-input" required><option value="">— Выберите водителя —</option><?php foreach($drivers as $x):?><option value="<?=$x['id']?>" <?=((int)($old['driver_id']??0)==(int)$x['id']?'selected':'')?>><?=e($x['full_name'])?> — <?=e($x['phone'])?></option><?php endforeach;?></select><?php if(!empty($errors['driver_id'])):?><div class="field-msg is-error"><?=e($errors['driver_id'])?></div><?php endif;?></div>
<div class="field"><label class="field-label">Водитель 2 <span class="text-muted">(необязательно)</span></label><select name="secondary_driver_id" class="field-input"><option value="">— Без второго водителя —</option><?php foreach($drivers as $x):?><option value="<?=$x['id']?>" <?=((int)($old['secondary_driver_id']??0)==(int)$x['id']?'selected':'')?>><?=e($x['full_name'])?> — <?=e($x['phone'])?></option><?php endforeach;?></select><?php if(!empty($errors['secondary_driver_id'])):?><div class="field-msg is-error"><?=e($errors['secondary_driver_id'])?></div><?php endif;?></div>
<div class="field"><label class="field-label">Транспорт (ТС)</label><select name="vehicle_set_id" class="field-input" required><?php foreach($vehicleSets as $x):?><option value="<?=$x['id']?>" <?=((int)($old['vehicle_set_id']??0)==(int)$x['id']?'selected':'')?>><?=e(ui_set_type($x['set_type']??null))?> — <?=e($x['primary_plate']??'—')?><?=!empty($x['secondary_plate'])?' + '.e($x['secondary_plate']):''?></option><?php endforeach;?></select></div>
</div><div class="form-section"><h3 class="panel-head-title">Статус</h3><select name="status" class="field-input"><option value="active" <?=($old['status']??'')==='active'?'selected':''?>>Активен</option><option value="inactive" <?=($old['status']??'')==='inactive'?'selected':''?>>Неактивен</option><option value="archived" <?=($old['status']??'')==='archived'?'selected':''?>>Архив</option></select></div>
<div class="form-section"><h3 class="panel-head-title">Комментарий</h3><textarea name="comments" class="field-textarea" rows="3"><?=e($old['comments']??'')?></textarea></div>
<div class="form-actions"><button type="submit" class="btn btn-primary">Сохранить изменения</button><a href="<?=app_url('/company/route-executors/'.$crewId)?>" class="btn btn-ghost">Отмена</a></div>
</div></form>
<?php endif;?>