<?php
$fmt = static fn($v) => \App\Service\FinanceEmployeePaymentService::formatMoney($v);
?>
<style>
.employee-payments-shell{max-width:1320px;margin:0 auto}.employee-payments-toolbar{display:flex;gap:8px}.employee-payments-filters{display:grid;grid-template-columns:minmax(220px,1.4fr) 180px 160px 160px auto;gap:10px;align-items:end;padding:12px 14px;background:var(--surface-form);border:1px solid var(--line-soft);margin-bottom:10px}.employee-payments-table tbody tr{cursor:pointer}.employee-payments-table tbody tr:hover{background:var(--surface-hover)}.employee-balance{font-weight:700}.employee-balance.is-zero{color:var(--text-faint)}.employee-balance.is-positive{color:var(--accent)}.employee-balance.is-negative{color:var(--danger)}.employee-payments-modal .modal{width:900px;max-width:calc(100vw - 32px)}@media(max-width:1050px){.employee-payments-filters{grid-template-columns:1fr 1fr}.employee-payments-filters .employee-filter-actions{grid-column:1/-1}}
</style>
<div class="employee-payments-shell">
 <div class="page-head">
  <div class="page-head-left"><h1 class="page-title">Выплаты сотрудникам</h1><div class="page-summary"><span>Сотрудники — все активные пользователи ERP текущей компании: руководители, логисты и другие пользователи.</span></div></div>
  <div class="page-head-actions employee-payments-toolbar"><button class="btn btn-primary btn--toolbar" type="button" data-employee-payment-create="PAYMENT">+ Выплата</button><button class="btn btn-secondary btn--toolbar" type="button" data-employee-payment-create="RETURN">+ Возврат</button></div>
 </div>
 <?php if(!empty($successFlash)): ?><div class="notice success"><?= e($successFlash) ?></div><?php endif; ?>
 <?php if(!empty($errorFlash)): ?><div class="notice warn"><?= e($errorFlash) ?></div><?php endif; ?>
 <form method="get" class="employee-payments-filters">
  <div class="field"><label class="field-label">Сотрудник</label><select class="field-select" name="employee_ref"><option value="">Все сотрудники</option><?php foreach($employees as $employee): ?><option value="<?= e($employee['ref']) ?>" <?= ($filters['employee_ref']??'')===$employee['ref']?'selected':'' ?>><?= e($employee['full_name']) ?></option><?php endforeach; ?></select></div>
  <div class="field"><label class="field-label">Источник</label><select class="field-select" name="source_type"><option value="">Все источники</option><option value="BANK" <?= ($filters['source_type']??'')==='BANK'?'selected':'' ?>>Расчётный счёт</option><option value="CASH" <?= ($filters['source_type']??'')==='CASH'?'selected':'' ?>>Касса</option></select></div>
  <div class="field"><label class="field-label">Дата с</label><input class="field-input" type="date" name="date_from" value="<?= e($filters['date_from']??'') ?>"></div>
  <div class="field"><label class="field-label">Дата по</label><input class="field-input" type="date" name="date_to" value="<?= e($filters['date_to']??'') ?>"></div>
  <div class="employee-filter-actions"><button class="btn btn-secondary" type="submit">Применить</button></div>
 </form>
 <div class="table-card table-card--standard">
  <div class="table-toolbar"><div class="table-toolbar-left"><strong>Взаиморасчёты по сотрудникам</strong></div></div>
  <?php if(empty($summaries)): ?><div class="ux-empty"><strong>Операций с сотрудниками пока нет</strong>Создайте выплату/возврат из кассы или свяжите существующую банковскую операцию.</div>
  <?php else: ?><div class="table-scroll"><table class="table employee-payments-table"><thead><tr><th>Сотрудник</th><th>Выплачено</th><th>Возвращено</th><th>Сальдо</th><th>Последняя операция</th></tr></thead><tbody><?php foreach($summaries as $row): $sign=\App\Service\FinanceEmployeePaymentService::moneySign($row['balance_amount']); [$identityType,$identityId]=explode(':',$row['employee_ref'],2); ?><tr data-employee-payment-row data-employee-type="<?= e($identityType) ?>" data-employee-id="<?= (int)$identityId ?>"><td><strong><?= e($row['full_name']) ?></strong><?php if((int)($row['posted_movement_count']??0)===0 && (int)($row['cancelled_movement_count']??0)>0): ?><div class="field-note">Только отменённые операции</div><?php endif; ?></td><td class="col-mono"><?= e($fmt($row['paid_amount'])) ?> ₽</td><td class="col-mono"><?= e($fmt($row['returned_amount'])) ?> ₽</td><td class="col-mono employee-balance <?= $sign===0?'is-zero':($sign>0?'is-positive':'is-negative') ?>"><?= e($fmt($row['balance_amount'])) ?> ₽</td><td><?= !empty($row['last_operation_date'])?e(date('d.m.Y',strtotime($row['last_operation_date']))):'—' ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
 </div>
</div>
<div id="employee-payment-create-modal" class="modal-overlay employee-payments-modal" role="dialog" aria-modal="true" data-close-on-overlay="0" data-close-on-escape="0"><div class="modal"><div class="modal-head"><span class="modal-title" id="employee-payment-create-title">Операция с сотрудником</span><button type="button" class="modal-close" data-close-modal="employee-payment-create-modal">&times;</button></div><div class="fs-remote-form" id="employee-payment-create-body"></div></div></div>
<div id="employee-payment-ledger-modal" class="modal-overlay employee-payments-modal" role="dialog" aria-modal="true" data-close-on-overlay="1" data-close-on-escape="1"><div class="modal modal-lg"><div class="modal-head"><span class="modal-title">Лицевой счёт сотрудника</span><button type="button" class="modal-close" data-close-modal="employee-payment-ledger-modal">&times;</button></div><div class="modal-body" id="employee-payment-ledger-body"></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const base=window.getErpBasePath?window.getErpBasePath():'';
 const initForm=(body)=>{const source=body.querySelector('[name="source_type"]');if(!source)return;const sync=()=>{body.querySelectorAll('[data-source-panel]').forEach(p=>{const on=p.dataset.sourcePanel===source.value;p.classList.toggle('is-hidden',!on);p.querySelectorAll('input,select,textarea').forEach(el=>{if(el.dataset.optionalAlways==='1')return;el.disabled=!on;});});};source.addEventListener('change',sync);sync();};
 document.querySelectorAll('[data-employee-payment-create]').forEach(btn=>btn.addEventListener('click',()=>{const type=btn.dataset.employeePaymentCreate;document.getElementById('employee-payment-create-title').textContent=type==='RETURN'?'Возврат от сотрудника':'Выплата сотруднику';const body=document.getElementById('employee-payment-create-body');body.innerHTML='<div class="modal-body"><div class="empty-state compact"><p>Загрузка...</p></div></div>';window.openModal('employee-payment-create-modal');fetch(base+'/company/finance/employee-payments/create?type='+encodeURIComponent(type),{credentials:'same-origin'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.text()}).then(html=>{body.innerHTML=html;initForm(body)}).catch(()=>body.innerHTML='<div class="modal-body"><div class="form-alert alert-error">Не удалось загрузить форму.</div></div>')}));
 document.querySelectorAll('[data-employee-payment-row]').forEach(row=>row.addEventListener('dblclick',()=>{const body=document.getElementById('employee-payment-ledger-body');body.innerHTML='<div class="empty-state compact"><p>Загрузка...</p></div>';window.openModal('employee-payment-ledger-modal');fetch(base+'/company/finance/employee-payments/employee/'+encodeURIComponent(row.dataset.employeeType)+'/'+encodeURIComponent(row.dataset.employeeId),{credentials:'same-origin'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.text()}).then(html=>body.innerHTML=html).catch(()=>body.innerHTML='<div class="form-alert alert-error">Не удалось загрузить журнал.</div>')}));
});
</script>
