<?php
use App\Service\FinanceCashFlowReportService;
$currentDateFrom=$_GET['date_from']??'';$currentDateTo=$_GET['date_to']??'';$currentMoneyAccountId=$_GET['money_account_id']??'';$currentDirection=$_GET['direction']??'all';$currentDdsCategoryId=$_GET['dds_category_id']??'';$currentSearch=$_GET['search']??'';
?>
<?php if($company===null):?><div class="notice warn">Компания не найдена.</div>
<?php elseif(($company['status']??'')!=='active'):?><div class="page-head"><div class="page-head-left"><h1 class="page-title">БДДС</h1></div></div><div class="notice warn">Работа с отчётом БДДС недоступна.</div>
<?php elseif($dbError!==null):?><div class="page-head"><div class="page-head-left"><h1 class="page-title">БДДС</h1></div></div><div class="notice warn"><?=e($dbError)?></div>
<?php else:?>
<div class="ux-shell" data-ux-page="cash-flow">
 <div class="page-head"><div class="page-head-left"><h1 class="page-title">БДДС</h1><div class="page-summary"><span>Фактическое движение денежных средств — от входящего остатка до исходящего.</span></div></div></div>
 <div class="ux-summary-strip"><div><strong>Как читать:</strong> поступления и расходы формируют чистый денежный поток; внутренние переводы показываются отдельно и не искажают результат.</div><div><?=count($rows??[])?> статей</div></div>
 <?php if(!empty($summary)):?>
 <div class="ux-kpi-grid cols-5">
  <div class="ux-kpi"><div class="ux-kpi-label">Входящий остаток</div><div class="ux-kpi-value"><?=FinanceCashFlowReportService::formatAmount($summary['opening_balance'])?></div><div class="ux-kpi-note">на начало периода</div></div>
  <div class="ux-kpi is-good"><div class="ux-kpi-label">Поступления</div><div class="ux-kpi-value"><?=FinanceCashFlowReportService::formatAmount($summary['total_income'])?></div><div class="ux-kpi-note">внешний денежный поток</div></div>
  <div class="ux-kpi is-bad"><div class="ux-kpi-label">Расходы</div><div class="ux-kpi-value"><?=FinanceCashFlowReportService::formatAmount($summary['total_expense'])?></div><div class="ux-kpi-note">внешний денежный поток</div></div>
  <div class="ux-kpi is-accent"><div class="ux-kpi-label">Чистый поток</div><div class="ux-kpi-value"><?=FinanceCashFlowReportService::formatAmount($summary['net_cash_flow'])?></div><div class="ux-kpi-note">поступления минус расходы</div></div>
  <div class="ux-kpi"><div class="ux-kpi-label">Исходящий остаток</div><div class="ux-kpi-value"><?=FinanceCashFlowReportService::formatAmount($summary['closing_balance'])?></div><div class="ux-kpi-note">на конец периода</div></div>
 </div>
 <?php endif;?>
 <form method="get" class="ux-filter-panel">
  <div class="ux-filter-head"><div class="ux-filter-title">Параметры отчёта</div><a href="<?=app_url('/company/finance/reports/cash-flow')?>" class="btn btn-ghost btn-sm">Сбросить</a></div>
  <div class="ux-filter-body">
   <div class="ux-filter-field"><label>С даты</label><input type="date" name="date_from" value="<?=e($currentDateFrom)?>" class="field-input"></div><div class="ux-filter-field"><label>По дату</label><input type="date" name="date_to" value="<?=e($currentDateTo)?>" class="field-input"></div>
   <div class="ux-filter-field"><label>Денежный счёт</label><select name="money_account_id" class="field-select"><option value="">Все счета</option><?php foreach(($moneyAccounts??[]) as $ma):?><option value="<?=e($ma['id'])?>"<?=$currentMoneyAccountId===(string)$ma['id']?' selected':''?>><?=e($ma['name'])?></option><?php endforeach;?></select></div>
   <div class="ux-filter-field"><label>Направление</label><select name="direction" class="field-select"><option value="all"<?=$currentDirection==='all'?' selected':''?>>Все</option><option value="INCOME"<?=$currentDirection==='INCOME'?' selected':''?>>Поступления</option><option value="EXPENSE"<?=$currentDirection==='EXPENSE'?' selected':''?>>Расходы</option></select></div>
   <div class="ux-filter-field"><label>Статья ДДС</label><select name="dds_category_id" class="field-select"><option value="">Все статьи</option><option value="null"<?=$currentDdsCategoryId==='null'?' selected':''?>>Без статьи</option><?php foreach(($ddsCategories??[]) as $dc):?><option value="<?=e($dc['id'])?>"<?=$currentDdsCategoryId===(string)$dc['id']?' selected':''?>><?=e($dc['name'])?></option><?php endforeach;?></select></div>
   <div class="ux-filter-field is-search"><label>Поиск по статье</label><input type="search" name="search" value="<?=e($currentSearch)?>" class="field-input" placeholder="Название статьи ДДС"></div><div class="ux-filter-actions"><button type="submit" class="btn btn-primary">Сформировать</button></div>
  </div>
 </form>
 <?php if(!empty($summary)):?><div class="ux-section"><div class="ux-section-head"><div><div class="ux-section-title">Справочные движения</div><div class="ux-section-sub">Не входят в чистый внешний денежный поток компании.</div></div></div><div class="ux-section-body"><div class="ux-summary-strip" style="margin:0"><div>Внутренние переводы: входящие <strong><?=FinanceCashFlowReportService::formatAmount($summary['transfer_in'])?></strong> · исходящие <strong><?=FinanceCashFlowReportService::formatAmount($summary['transfer_out'])?></strong> · нетто <strong><?=FinanceCashFlowReportService::formatAmount($summary['transfer_net'])?></strong></div><div>Корректировки: <strong><?=FinanceCashFlowReportService::formatAmount($summary['adjustment_total'])?></strong></div></div></div></div><?php endif;?>
 <div class="ux-table"><div class="ux-table-head"><div><div class="ux-table-title">Движение по статьям ДДС</div><div class="ux-table-meta">Нажмите на статью, чтобы открыть операции за выбранный период.</div></div><div class="ux-table-meta">Показано: <?=count($rows??[])?></div></div>
 <?php if(empty($rows)):?><div class="ux-empty"><strong>Нет операций за период</strong>Измените фильтры или дождитесь проведённых банковских операций.</div><?php else:?><div class="table-scroll"><table class="table"><thead><tr><th>Статья ДДС</th><th>Направление</th><th>Поступления</th><th>Расходы</th><th>Нетто</th><th>Операций</th></tr></thead><tbody>
 <?php foreach($rows as $r):$linkParams='date_from='.urlencode($currentDateFrom?:date('Y-m-01')).'&date_to='.urlencode($currentDateTo?:date('Y-m-t'));if(($r['direction']??'')==='INCOME')$linkParams.='&type=INCOME';elseif(($r['direction']??'')==='EXPENSE')$linkParams.='&type=EXPENSE';?><tr><td><div class="ux-primary-cell"><strong><?php if(!empty($r['is_uncategorized'])):?><?=e($r['name'])?><?php else:?><a href="<?=app_url('/company/finance/operations?'.$linkParams)?>" class="link"><?=e($r['name'])?></a><?php endif;?></strong><span><?=!empty($r['is_uncategorized'])?'Требует разнесения':'Классифицировано'?></span></div></td><td><?php if(($r['direction']??'')==='INCOME'):?><span class="badge badge-ok"><span class="dot"></span>Поступление</span><?php elseif(($r['direction']??'')==='EXPENSE'):?><span class="badge badge-danger"><span class="dot"></span>Расход</span><?php else:?><span class="badge badge-neutral"><span class="dot"></span>Оба</span><?php endif;?></td><td class="col-mono ux-money-good"><?=FinanceCashFlowReportService::formatAmount($r['fact_income'])?></td><td class="col-mono ux-money-bad"><?=FinanceCashFlowReportService::formatAmount($r['fact_expense'])?></td><td class="col-mono"><strong><?=FinanceCashFlowReportService::formatAmount($r['net_flow'])?></strong></td><td class="col-mono"><?=(int)$r['operation_count']?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>
</div>
<?php endif;?>