<?php
if(PHP_SAPI!=='cli'){fwrite(STDERR,"CLI only.\n");exit(1);} $envRoot=getenv('PLANEX_ROOT');$argRoot=isset($argv[1])?$argv[1]:'';$root=rtrim((string)($envRoot!==false&&$envRoot!==''?$envRoot:$argRoot),'/');if($root===''||!is_file($root.'/bootstrap/app.php'))throw new RuntimeException('PLANEX_ROOT is invalid.');
require_once $root.'/app/Support/helpers.php';require_once $root.'/app/Support/environment.php';loadEnvFileNonOverwriting($root.'/.env');$config=require $root.'/bootstrap/app.php';require_once $root.'/app/Support/entrypoint_dependencies.php';
$name='076_finance_employee_money_accounts.sql';$path=$root.'/database/migrations-local/'.$name;$sql=file_get_contents($path);if($sql===false||trim($sql)==='')throw new RuntimeException('Migration 076 missing.');$checksum=hash('sha256',$sql);
$central=(new \App\Core\Database($config['database']))->connection();$companies=$central->query("SELECT * FROM companies WHERE status='active' ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);if(!$companies)throw new RuntimeException('No active companies.');$applied=0;$existing=0;
foreach($companies as $company){$companyId=(int)(isset($company['id'])?$company['id']:0);if($companyId<=0)throw new RuntimeException('Invalid company id.');$pdo=(new \App\Core\Database(companyDatabaseConfig($config,$company)))->connection();$dbName=(string)$pdo->query('SELECT DATABASE()')->fetchColumn();if($dbName==='')throw new RuntimeException('Cannot resolve tenant DB.');
$pdo->exec("CREATE TABLE IF NOT EXISTS schema_migrations (id INT UNSIGNED NOT NULL AUTO_INCREMENT,migration VARCHAR(255) NOT NULL,checksum VARCHAR(64) NOT NULL,executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uk_local_migration(migration)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$lockName='planex_finance_direct_076_'.substr(hash('sha256',$dbName),0,24);$lock=$pdo->prepare('SELECT GET_LOCK(?,10)');$lock->execute(array($lockName));if((int)$lock->fetchColumn()!==1)throw new RuntimeException('Cannot acquire migration lock company '.$companyId);
try{$stmt=$pdo->prepare('SELECT checksum FROM schema_migrations WHERE migration=? LIMIT 1');$stmt->execute(array($name));$stored=$stmt->fetchColumn();if($stored!==false){if((string)$stored!==$checksum)throw new RuntimeException('Migration checksum mismatch company '.$companyId);$existing++;}else{$newer=$pdo->query("SELECT COUNT(*) FROM schema_migrations WHERE migration REGEXP '^[0-9]{3}_' AND CAST(LEFT(migration,3) AS UNSIGNED)>76");if((int)$newer->fetchColumn()!==0)throw new RuntimeException('Newer migration exists while 076 absent company '.$companyId);$pdo->exec($sql);$ins=$pdo->prepare('INSERT INTO schema_migrations(migration,checksum) VALUES(?,?)');$ins->execute(array($name,$checksum));$applied++;}
$table=$pdo->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='finance_employee_money_accounts'");if((int)$table->fetchColumn()!==1)throw new RuntimeException('Employee account table missing company '.$companyId);$cols=$pdo->query("SELECT COUNT(DISTINCT COLUMN_NAME) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='finance_employee_money_accounts' AND COLUMN_NAME IN ('money_account_id','employee_identity_type','employee_identity_id','employee_name_snapshot','is_active')");if((int)$cols->fetchColumn()!==5)throw new RuntimeException('Employee account table shape invalid company '.$companyId);printf("FINANCE_DIRECT_076_COMPANY_OK id=%d db=%s state=%s\n",$companyId,$dbName,$stored===false?'applied':'existing');}catch(Exception $e){throw $e;} $release=$pdo->prepare('SELECT RELEASE_LOCK(?)');$release->execute(array($lockName));}
printf("FINANCE_DIRECT_076_OK applied=%d existing=%d companies=%d checksum=%s\n",$applied,$existing,count($companies),$checksum);
