<?php
require_once __DIR__.'/../app/Support/helpers.php';require_once __DIR__.'/../app/Support/environment.php';loadEnvFileNonOverwriting(dirname(__DIR__).'/.env');$config=require __DIR__.'/../bootstrap/app.php';require_once base_path('app/Support/entrypoint_dependencies.php');
$name='063_finance_matching_classification.sql';$path=base_path('database/migrations-local/'.$name);$sql=file_get_contents($path);if($sql===false||trim($sql)==='')throw new RuntimeException('Migration missing.');$checksum=hash('sha256',$sql);$central=(new \App\Core\Database($config['database']))->connection();$companies=$central->query("SELECT * FROM companies WHERE status='active' ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);$applied=$existing=0;
foreach($companies as $company){$pdo=(new \App\Core\Database(companyDatabaseConfig($config,$company)))->connection();$pdo->exec("CREATE TABLE IF NOT EXISTS schema_migrations (id INT UNSIGNED NOT NULL AUTO_INCREMENT,migration VARCHAR(255) NOT NULL,checksum VARCHAR(64) NOT NULL,executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uk_local_migration(migration)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$lockName='planex_p41_'.substr(hash('sha256',(string)$pdo->query('SELECT DATABASE()')->fetchColumn()),0,32);$lock=$pdo->prepare('SELECT GET_LOCK(?,10)');$lock->execute([$lockName]);if((int)$lock->fetchColumn()!==1)throw new RuntimeException('Cannot acquire tenant migration lock.');
 try{$s=$pdo->prepare('SELECT checksum FROM schema_migrations WHERE migration=?');$s->execute([$name]);$stored=$s->fetchColumn();if($stored!==false){if(!hash_equals((string)$stored,$checksum))throw new RuntimeException('Migration checksum mismatch company '.(int)$company['id']);$existing++;}else{$pdo->exec($sql);$s=$pdo->prepare('INSERT INTO schema_migrations(migration,checksum) VALUES(?,?)');$s->execute([$name,$checksum]);$applied++;}
  $required=[['TABLES','TABLE_NAME','finance_cash_flow_centers'],['COLUMNS','COLUMN_NAME','classification_status'],['COLUMNS','COLUMN_NAME','classification_locked']];foreach($required as [$kind,$column,$value]){$table=$kind==='TABLES'?'finance_cash_flow_centers':'bank_transactions';$q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.$kind WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND $column=?");$q->execute([$table,$value]);if((int)$q->fetchColumn()!==1)throw new RuntimeException("Schema verification failed: $table.$value");}
  $q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='finance_matching_rules' AND COLUMN_NAME='target_cash_account_id'");$q->execute();if((int)$q->fetchColumn()!==1)throw new RuntimeException('Rule schema verification failed.');
 }finally{$release=$pdo->prepare('SELECT RELEASE_LOCK(?)');$release->execute([$lockName]);}}
printf("P41_FINANCE_MIGRATION_OK companies=%d applied=%d existing=%d checksum=%s\n",count($companies),$applied,$existing,$checksum);
